<?php
/** @var \Mwop\Art\Photo $photo */
$this->layout('layout::layout', [
    'title'  => $this->escapeHtml('Art: ' . $photo->filename()),
    'layout' => 'large',
]);

$pageUrl = $this->serverurl($this->url('art.photo', ['image' => $photo->filename()]));

$matches = [];
$tags    = [];
if (preg_match_all('/\#(?<tag>\S+)/', $photo->description, $matches)) {
    foreach ($matches['tag'] as $tag) {
        $tags[] = $tag;
    }
}

$this->push('links');
?>
    <!-- OpenGraph -->
    <link rel="canonical" href="<?= $pageUrl ?>" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:creator" content="@mwop" />
    <meta property="og:site_name" content="mwop.net" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?= strtr('Original art by Matthew Weier O\'Phinney: ' . $photo->filename(), '"', "'") ?>" />
    <meta property="og:url" content="<?= $pageUrl ?>" />
    <meta property="og:image" content="<?= $this->serverurl($this->url('art.image', ['type' => 'thumbnails', 'image' => $photo->filename()])) ?>" />
    <meta property="og:image:alt" content="<?= strtr('Original art by Matthew Weier O\'Phinney: ' . $photo->filename(), '"', "'") ?>" />
    <meta property="og:description" content="<?= strtr(substr($photo->description, 0, 150), '"', "'") . '...' ?>" />
    <meta property="article:published_time" content="<?= $photo->createdAt->format('c') ?>" />
    <?php foreach ($tags as $tag): ?>
    <meta property="article:tag" content="<?= $this->escapeHtmlAttr($tag) ?>" />
    <?php endforeach ?>
<?php $this->end(); ?>

<nav class="w-full p-2 bg-mwop-nav rounded" aria-label="breadcrumb">
    <ol class="list-none inline">
        <li class="inline"><a class="text-mwop-fg font-semibold" href="<?= $this->url('art.gallery') ?>">Gallery</a></li>
        <li class="inline text-mwop-light before:content-[attr(before)]" aria-current="page" before=" / "><?= $photo->filename() ?></li>
    </ol>
</nav>

<article class="w-full my-4 mx-auto p-4 bg-mwop-nav rounded-lg">
    <p class="text-2xl"><?= $this->escapeHtml($photo->description) ?></p>

    <img class="w-full p-4" src="<?= $this->url('art.image', ['type' => 'fullsize', 'image' => $photo->filename()]) ?>" alt="Original art by Matthew Weier O'Phinney">

    <p class="border-b border-mwop-nav pb-4 text-mwop-light">
        Posted <?= $photo->createdAt->format('l, F j, Y') ?>
    </p>

    <div class="text-center">
        <a class="no-underline" href="https://twitter.com/intent/tweet?url=<?= $pageUrl ?>&text=<?= $this->escapeHtmlAttr('Photo by @mwop') ?>"><i class="fa-brands fa-twitter fa-2xl"></i></a>
        <a class="no-underline" href="https://www.facebook.com/sharer.php?u=<?= $pageUrl ?>"><i class="fa-brands fa-facebook fa-2xl"></i></a>
        <a class="no-underline" href="https://pinterest.com/pin/create/link/?url=<?= $pageUrl?>&description=<?= $this->escapeHtmlAttr('Photo by @mwop') ?>"><i class="fa-brands fa-pinterest fa-2xl"></i></a>
    </div>
</article>
