<?php
/** @var \Mwop\Art\Photo $photo */
$this->layout('layout::layout', [
    'title' => $this->escapeHtml('Art: ' . $photo->filename()),
]);

$pageUrl = $this->serverurl($this->url('art.photo', ['image' => $photo->filename()]));

$matches = [];
$tags    = [];
if (preg_match_all('/\#(?<tag>\S+)/', $photo->description, $matches)) {
    foreach ($matches['tag'] as $tag) {
        $tags[] = $tag;
    }
}

$this->push('links');
?>
    <!-- OpenGraph -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:creator" content="@mwop" />
    <meta property="og:site_name" content="mwop.net" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?= $this->escapeHtmlAttr('Original art by Matthew Weier O\'Phinney: ' . $photo->filename()) ?>" />
    <meta property="og:url" content="<?= $pageUrl ?>" />
    <meta property="og:image" content="<?= $this->serverurl($this->url('art.image', ['type' => 'thumbnails', 'image' => $photo->filename()])) ?>" />
    <meta property="og:image:alt" content="<?= $this->escapeHtmlAttr('Original art by Matthew Weier O\'Phinney: ' . $photo->filename()) ?>" />
    <meta property="article:published_time" content="<?= $photo->createdAt->format('c') ?>" />
    <?php foreach ($tags as $tag): ?>
    <meta property="article:tag" content="<?= $this->escapeHtmlAttr($tag) ?>" />
    <?php endforeach ?>
<?php
$this->end();


?>
<div class="container-fluid photo">
    <nav class="row" aria-label="breadcrumb">
        <ol class="breadcrumb col-md-8 offset-md-2">
            <li class="breadcrumb-item"><a href="<?= $this->url('art.gallery') ?>">Gallery</a></li>
            <li class="breadcrumb-item active" aria-current="page"><?= $photo->filename() ?></li>
        </ol>
    </nav>

    <div class="row">
        <div class="card col-md-8 offset-md-2">
            <div class="card-body">
                <p class="card-text"><?= $this->escapeHtml($photo->description) ?></p>
            </div>

            <img class="card-img-bottom" src="<?= $this->url('art.image', ['type' => 'fullsize', 'image' => $photo->filename()]) ?>" alt="Original art by Matthew Weier O'Phinney">

            <div class="card-footer text-muted">
                Posted <?= $photo->createdAt->format('l, F j, Y') ?>
            </div>

            <div class="card-footer text-center fs-1">
                <a href="https://twitter.com/intent/tweet?url=<?= $pageUrl ?>&text=<?= $this->escapeHtmlAttr('Photo by @mwop') ?>"><i class="fa-brands fa-twitter"></i></a>
                <a href="https://www.facebook.com/sharer.php?u=<?= $pageUrl ?>"><i class="fa-brands fa-facebook"></i></a>
                <a href="https://pinterest.com/pin/create/link/?url=<?= $pageUrl?>&description=<?= $this->escapeHtmlAttr('Photo by @mwop') ?>"><i class="fa-brands fa-pinterest"></i></a>
            </div>
        </div>
    </div>
</div></div>
