<?php
/** @var \Mwop\Art\Photo $photo */
$this->layout('layout::layout', [
    'title'  => $this->escapeHtml('Art: Upload new photo'),
    'layout' => 'large',
]);
?>
<?php if (isset($error)): ?>
    <div class="w-full mb-4 p-4 bg-red-700 text-white text-center">
        <h4>Error processing image</h4>
        <p><?= $this->escapeHtml($error) ?></p>
    </div>
<?php endif ?>

<h3 class="w-full text-center">Upload new artwork</h3>

<form class="flex flex-row justify-center items-stretch gap-0 border-none" method="post" action="<?= $this->url('art.photo.upload.process') ?>" enctype="multipart/form-data">

<div class="w-2/5 flex items-center p-0 bg-neutral-700">
    <div class="relative min-h-full min-w-full p-4 rounded-l-lg border border-neutral-400 text-center">
        <input class="absolute w-max h-max top-0 left-0 right-0 bottom-0 opacity-0 cursor-pointer focus:outline-2 focus:outline-neutral-100 focus:ring-4 valid:border-neutral-200" type="file" accept="image/jpeg,image/png,image/webp" name="imageUpload" required="required">
        <div class="mwop-art-upload-content min-w-full px-3 py-4 bg-transparent border-2 border-neutral-400 border-dashed transition ease-in-out delay-300 hover:border-neutral-100">
            <div class="default h-2 pt-[50%] pb-[50%] valid:hidden"><i class="fa fa-cloud-arrow-up fa-2xl fs-1"></i><br />Drag and drop, or click to select</div>
            <div class="complete h-2 pt-[50%] pb-[50%] hidden valid:block valid:text-[5em]"><i class="fa fa-circle-check fa-2xl text-emerald-600"></i></div>
        </div>
    </div>
</div>

<div class="w-2/5 rounded-r-lg border border-neutral-400 p-4 font-semibold">
    <div class="mb-3">
        <label class="block mb-2 text-xl" for="mwopArtUploadDescription">Description</label>
        <textarea class="min-w-full p-2 bg-neutral-100 text-neutral-900 border-neutral-900 rounded-lg" rows="10" name="description" id="mwopArtUploadDescription"><?= isset($form['description']) ? $this->escapeHtml($form['description']) : '' ?></textarea>
    </div>

    <button class="bg-neutral-700 border-neutral-900 rounded p-2 hover:bg-neutral-300 hover:text-neutral-900 active:bg-neutral-100 active:text-neutral-900" type="submit">Submit</button>
</div>
</form>
