<?php
return array (
  'CommonResource\\Mongo' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'Mongo.php',
  'CommonResource\\MongoDB' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'MongoDB.php',
  'CommonResource\\MongoCollection' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'MongoCollection.php',
  'CommonResource\\Entity' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'Entity.php',
  'CommonResource\\Resource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'Resource.php',
  'CommonResource\\Filter\\Timezone' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'Filter' . DIRECTORY_SEPARATOR . 'Timezone.php',
  'CommonResource\\Filter\\Timestamp' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'Filter' . DIRECTORY_SEPARATOR . 'Timestamp.php',
  'CommonResource\\Resource\\Collection' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Collection.php',
  'CommonResource\\Resource\\MongoCollection' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'MongoCollection.php',
  'CommonResource\\Resource\\AbstractResource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'AbstractResource.php',
  'CommonResource\\Query' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'Query.php',
  'CommonResource\\DataSource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'DataSource.php',
  'CommonResource\\DataSource\\Mongo' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'DataSource' . DIRECTORY_SEPARATOR . 'Mongo.php',
  'CommonResource\\DataSource\\Mock' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'DataSource' . DIRECTORY_SEPARATOR . 'Mock.php',
  'CommonResource\\DataSource\\Query' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'DataSource' . DIRECTORY_SEPARATOR . 'Query.php',
  'CommonResource\\DataSource\\Where' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'DataSource' . DIRECTORY_SEPARATOR . 'Where.php',
  'CommonResource\\DataSource\\Mongo\\QueryParser' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'DataSource' . DIRECTORY_SEPARATOR . 'Mongo' . DIRECTORY_SEPARATOR . 'QueryParser.php',
  'CommonResource\\ResourceCollection' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'ResourceCollection.php',
  'CommonResource\\ArraySerializable' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'ArraySerializable.php',
  'CommonResource\\Validatible' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'CommonResource' . DIRECTORY_SEPARATOR . 'Validatible.php',
);
