<?php
$this->layout('layout::layout', [
    'title' => 'Contact',
]);
$this->start('scripts');
?>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<?php $this->stop() ?>
<section class="col-md-6 contact">
    <h2>Contact Me</h2>

    <p>
        Feel free to contact me. Please note, however, that I likely will not 
        respond to recruiters, nor to questions that could be asked in public
        forums.
    </p>

    <?php if ($error) : ?>
    <p class="error">
        There were one or more isues with your submission. Please correct them as 
        indicated below.
    </p>

    <pre>
        <?= $this->escapeHtml($error['message']) ?>
    </pre>

    <?php endif ?>

    <form method="post" name="contact" action="<?= $this->url('contact.process') ?>" id="contact">
        <div class="form-group">
            <label for="from">From (email):</label>
            <input class="form-control" type="text" name="from" value="">
        </div>

        <div class="form-group">
            <label for="subject">Subject:</label>
            <input class="form-control" type="text" name="subject" value="">
        </div>

        <div class="form-group">
            <label for="body">Your message:</label>
            <textarea class="form-control" rows="10" name="body"></textarea>
        </div>

        <div
            class="form-group g-recaptcha"
            data-sitekey="<?= $recaptcha_pub_key ?>"
            data-theme="light"></div>

        <input type="hidden" name="csrf" value="<?= $csrf ?>">
        <button type="submit" class="btn btn-outline-secondary" name="Send">Send</button>
    </form>
</section>
