<?php
$this->layout('layout::layout', [
    'title'  => 'Contact',
    'layout' => 'medium',
]);
$this->start('scripts');
?>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<?php $this->stop() ?>
<h2>Contact Me</h2>

<p>
    Feel free to contact me. Please note, however, that I likely will not 
    respond to recruiters, nor to questions that could be asked in public
    forums.
</p>

<?php if (isset($error)) : ?>
<p class="text-red-700 font-semibold">
    There were one or more isues with your submission. Please correct them as 
    indicated below.
</p>

<pre class="font-mono">
    <?= $this->escapeHtml($error['message']) ?>
</pre>
<?php endif ?>

<form class="bg-mwop-nav p-4 w-full rounded-lg" method="post" name="contact" action="<?= $this->url('contact.process') ?>" id="contact">
    <label class="label" for="from">From (email):</label>
    <input class="text-input" type="text" name="from" value="" required="required">

    <label class="label" for="subject">Subject:</label>
    <input class="text-input" type="text" name="subject" value="" required="required">

    <label class="label" for="body">Your message:</label>
    <textarea class="textarea h-48" name="body" required="required"></textarea>

    <div
        class="g-recaptcha my-4"
        data-sitekey="<?= $recaptcha_pub_key ?>"
        data-theme="dark"></div>

    <input type="hidden" name="csrf" value="<?= $csrf ?>">
    <button class="btn" type="submit" name="Send">Send</button>
</form>
