<?php $this->layout('layout::layout', [
    'title'  => 'Thank You',
    'layout' => 'small',
]) ?>
<h2>Thank you!</h2>

<p>
    Your message has been sent!
</p>

<div class="bg-mwop-nav mt-4 p-4 w-full rounded-lg">
    <p>Want to reach me quicker?</p>

    <p class="text-center">
        <a class="no-underline" href="https://phpc.social/@mwop"><i class="fa-brands fa-mastodon fa-2xl"></i></a>
    </p>
</div>
