version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/mwop.net
permissions:
    - object: /var/www/mwop.net
      pattern: "**"
      owner: www-data
      group: www-data
      mode: 4750
      type:
        - directory
    - object: /var/www/mwop.net
      pattern: "**"
      owner: www-data
      group: www-data
      mode: 640
      type:
        - file
hooks:
  ApplicationStop:
    - location: .aws/application-stop.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: .aws/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: .aws/after-install-www-data.sh
      timeout: 300
      runas: www-data
    - location: .aws/after-install-root.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: .aws/application-start.sh
      timeout: 30
      runas: root
