<?php 
use Zend\Stdlib\ArrayUtils;
$paginatorUrl          = $this->paginator_url;
$urlSubstitutionString = $this->substitution;
$basePageUrl           = str_replace('-p%d', '', $paginatorUrl);
if ($urlSubstitutionString) {
    $basePageUrl = str_replace('%s', $urlSubstitutionString, $basePageUrl);
}
$this->headTitle()->prepend($this->title);
$this->headLink(array(
    // this should be something like blog.xml -- broken right now
    'href'  => $paginatorUrl . '.xml',
    'type'  => 'application/atom+xml',
    'rel'   => 'alternate',
    'title' => $this->title . ' Atom Feed',
));
$this->headLink(array(
    'href'  => $paginatorUrl . '.xml?type=rss',
    'type'  => 'application/rss+xml',
    'rel'   => 'alternate',
    'title' => $this->title . ' RSS Feed',
));
?>
<div class="row">
<section class="eleven columns alpha blog">
    <h2><?php echo $this->title ?></h2>

<?php 
foreach ($this->entries as $entry) {
    echo '<div class="row clearfix">', "\n";
    echo $this->render('blog/entry-short', array('entry' => $entry));
    echo '</div>', "\n";
}

echo $this->paginationControl($this->entries, 'Sliding', 'blog/paginator', array('url' => $paginatorUrl, 'substitution' => $urlSubstitutionString));
?>
</section>

<aside class="four columns offset-by-one omega sidebar blog">
    <?php echo $this->render('blog/blogroll') ?>
</aside>
</div>
