<?php
return array (
  'PhlyCommon\\Mongo' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'Mongo.php',
  'PhlyCommon\\MongoDB' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'MongoDB.php',
  'PhlyCommon\\MongoCollection' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'MongoCollection.php',
  'PhlyCommon\\Entity' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'Entity.php',
  'PhlyCommon\\Resource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'Resource.php',
  'PhlyCommon\\Filter\\Timezone' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'Filter' . DIRECTORY_SEPARATOR . 'Timezone.php',
  'PhlyCommon\\Filter\\Timestamp' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'Filter' . DIRECTORY_SEPARATOR . 'Timestamp.php',
  'PhlyCommon\\Resource\\Collection' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'Collection.php',
  'PhlyCommon\\Resource\\MongoCollection' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'MongoCollection.php',
  'PhlyCommon\\Resource\\AbstractResource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR . 'AbstractResource.php',
  'PhlyCommon\\Query' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'Query.php',
  'PhlyCommon\\DataSource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'DataSource.php',
  'PhlyCommon\\DataSource\\Mongo' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'DataSource' . DIRECTORY_SEPARATOR . 'Mongo.php',
  'PhlyCommon\\DataSource\\Mock' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'DataSource' . DIRECTORY_SEPARATOR . 'Mock.php',
  'PhlyCommon\\DataSource\\Query' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'DataSource' . DIRECTORY_SEPARATOR . 'Query.php',
  'PhlyCommon\\DataSource\\Where' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'DataSource' . DIRECTORY_SEPARATOR . 'Where.php',
  'PhlyCommon\\DataSource\\Mongo\\QueryParser' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'DataSource' . DIRECTORY_SEPARATOR . 'Mongo' . DIRECTORY_SEPARATOR . 'QueryParser.php',
  'PhlyCommon\\ResourceCollection' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'ResourceCollection.php',
  'PhlyCommon\\ArraySerializable' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'ArraySerializable.php',
  'PhlyCommon\\Validatible' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyCommon' . DIRECTORY_SEPARATOR . 'Validatible.php',
);
