<?php
$this->layout('layout::layout', [
    'title' => $this->escapeHtml($title),
]);

$this->push('links');
if (isset($tag)) :
?>
    <link href="<?= $this->serverurl($rss) ?>" rel="alternate" type="application/rss+xml" title="phly, boy, phly RSS Feed for <?= $this->escapeHtmlAttr($tag) ?>">
    <link href="<?= $this->serverurl($atom) ?>" rel="alternate" type="application/atom+xml" title="phly, boy, phly Atom Feed for <?= $this->escapeHtmlAttr($tag) ?>">
<?php
endif;
$this->end();

$this->push('scripts');
echo '<script src="/assets/js/prism.js"></script>';
$this->end();

$this->push('footer');
echo $this->fetch('data::tag-cloud');
$this->end();
?>
<section class="w-full px-4 lg:w-3/4 lg:px-0 mt-24 mb-4 mx-auto">
    <h2><?= $this->escapeHtml($title) ?></h2>

    <?php if (empty($posts)) : ?>
    <p class="text-center">No posts found.</p>

    <?php else : ?>
    <?php foreach ($posts as $post) : ?>
    <div class="md:flex md:flex-row-reverse md:justify-end md:justify-items-start md:content-start md:items-start md:gap-8 h-entry">
        <section class="w-full md:w-3/4 md:mb-8 md:border-b md:border-dotted">
            <h4 class=""><a class="u-url u-uid" href="<?= $this->postUrl($post) ?>"><?= $this->escapeHtml($post->title) ?></a></h4>

            <div class="entry body p-summary"><?= $post->body ?></div>

            <p><a href="<?= $this->postUrl($post) ?>">Continue reading...</a></p>
        </section>

        <aside class="w-full md:w-1/4 mb-8 border-b border-dotted md:mb-0 md:border-none italic">
            <p>
                Written on <time class="dt-published" datetime="<?= $this->formatDateRfc($post->created) ?>"><?= $this->formatDate($post->created) ?></time>.
            <?php if ($post->updated) : ?>
                <br />Last updated on <time class="dt-updated" datetime="<?= $this->formatDateRfc($post->updated) ?>"><?= $this->formatDate($post->updated) ?></time>.
            <?php endif ?>
            </p>

            <ul>
            <?php foreach ($this->processTags($post->tags) as $tag) : ?>
                <li><a class="p-category" href="<?= $tag->link ?>"><?= $tag->name ?></a>
            <?php endforeach ?>
            </ul>

            <div class="hidden p-author h-card">
                Posted by <a rel="author" class="u-url" href="<?= $this->serverurl() ?>">Matthew Weier O'Phinney</a>,
                <img class="u-photo" width="50" src="https://avatars0.githubusercontent.com/u/25943?v=3&u=79dd2ea1d4d8855944715d09ee4c86215027fa80&s=140" alt="mwop">
            </div>
        </aside>
    </div>
    <?php endforeach ?>

    <?php $this->insert('mwop::pagination', ['pagination' => $pagination]) ?>

    <?php endif ?>
</section>
