<?php
$this->layout('layout::layout', [
    'title' => $this->escapeHtml($post->title),
]);

$imageAltText = null === $post->image
    ? 'mwop.net celtic knot logo'
    : sprintf(
        "'%s' by %s; licensed under %s",
        $post->image->title,
        $post->image->creator,
        strtoupper($post->image->license),
    );

$this->push('links');
?>
    <!-- OpenGraph -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:creator" content="@mwop" />
    <meta property="og:site_name" content="mwop.net" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?= $this->escapeHtmlAttr($post->title) ?>" />
    <meta property="og:url" content="<?= $this->serverurl($this->postUrl($post)) ?>" />
    <meta property="og:image" content="<?= $post->image ? $post->image->url : $this->serverurl('/images/logo.png') ?>" />
    <meta property="og:image:alt" content="<?= $this->escapeHtmlAttr($imageAltText) ?>" />
    <meta property="article:published_time" content="<?= $post->created->format('c') ?>" />
    <meta property="article:modified_time" content="<?= $post->updated->format('c') ?>" />
    <?php foreach ($post->tags as $tag): ?>
    <meta property="article:tag" content="<?= $this->escapeHtmlAttr($tag) ?>" />
    <?php endforeach ?>
<?php foreach ($this->processTags($post->tags) as $tag): ?>
    <!-- Feeds -->
    <link href="<?= $this->serverurl($tag->rss) ?>" rel="alternate" type="application/rss+xml" title="phly, boy, phly RSS Feed for <?= $tag->name ?>">
    <link href="<?= $this->serverurl($tag->atom) ?>" rel="alternate" type="application/rss+xml" title="phly, boy, phly RSS Feed for <?= $tag->name ?>">
<?php endforeach; ?>
<?php
$this->end();

$this->push('scripts');
echo '<script src="/js/prism.js"></script>';
echo '<script src="/js/disqus.js"></script>';
$this->end();

$this->push('footer');
$this->insert('data::tag-cloud');
$this->end();
?>
<div class="single-entry h-entry container col offset-md-2"><div class="row">
    <aside class="col-md-2 d-none d-sm-block sidebar blog">
        <p>
            Written on <time class="dt-published" datetime="<?= $this->formatDateRfc($post->created) ?>"><?= $this->formatDate($post->created) ?></time>.
            <?php if ($post->updated) : ?>
            <br />Last updated on <time class="dt-updated" datetime="<?= $this->formatDateRfc($post->updated) ?>"><?= $this->formatDate($post->updated) ?></time>.
            <?php endif ?>
        </p>

        <ul class="tags">
        <?php foreach ($this->processTags($post->tags) as $tag) : ?>
            <li><a class="p-category" href="<?= $tag->link ?>"><?= $tag->name ?></a>
        <?php endforeach ?>
        </ul>

    <?php if (null !== $post->image) : ?>
        <p>
            Image by <a href="<?= $post->image->creditUrl ?>"><?= $post->image->creator ?></a>,
            licensed under <a href="<?=$post->image->licenseUrl ?>"><?= strtoupper($post->image->license) ?></a>
        </p>
    <?php endif ?>
    </aside>

    <article class="col-md-8 blog">
    <?php if (null === $post->image) : ?>
        <h2 class="p-name"><a class="u-url u-uid" href="<?= $this->postUrl($post) ?>"><?= $this->escapeHtml($post->title) ?></a></h2>
    <?php else : ?>
        <section class="banner">
            <img class="float-end" src="<?= $post->image->url ?>" alt="<?= $post->image->title ?>">
            <h2 class="p-name"><a class="u-url u-uid" href="<?= $this->postUrl($post) ?>"><?= $this->escapeHtml($post->title) ?></a></h2>
        </section>
    <?php endif ; ?>

        <div class="e-content">
        <?= $post->body ?>

        <?= $post->extended ?>
        </div>

        <div class="p-author h-card d-none">
          Posted by <a class="p-name u-url" href="<?= $this->serverurl() ?>">Matthew Weier O'Phinney</a>,
          <img class="u-photo photo" width="50" src="https://avatars0.githubusercontent.com/u/25943?v=3&u=79dd2ea1d4d8855944715d09ee4c86215027fa80&s=140" alt="mwop">
        </div>

        <?php /*
        <div class="divider"></div>

        <h3 class="text-center"><em>Like this content?</em></h3>

        <p class="text-center"><a href="https://www.patreon.com/mwop"><img src="/images/become_a_patron_button@2x.png" alt="Become a Patron!" /></a></p>
         */ ?>

        <div class="divider"></div>

        <div id="disqus_thread"
          data-developer="<?= $disqus['developer'] ?>"
          data-url="<?= $this->serverurl($this->postUrl($post)) ?>"
          data-identifier="<?= $post->id ?>"
          data-title="<?= $post->title ?>"
          data-key="<?= $disqus['key'] ?>"></div>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
    </article>
</div></div>
