<?php
$this->layout('layout::layout', [
    'title' => $this->escapeHtml($post->title),
]);

$this->start('styles');
$this->insert('blog::styles');
$this->stop();

$this->push('links');
?>
    <link rel="amphtml" href="<?= $this->serverurl($this->postUrl($post)) ?>?amp=1">
<?php foreach ($this->processTags($post->tags) as $tag) : ?>
    <link href="<?= $this->serverurl($tag->rss) ?>" rel="alternate" type="application/rss+xml" title="phly, boy, phly RSS Feed for <?= $tag->name ?>">
    <link href="<?= $this->serverurl($tag->atom) ?>" rel="alternate" type="application/rss+xml" title="phly, boy, phly RSS Feed for <?= $tag->name ?>">
<?php endforeach;
$this->end();

$this->push('scripts');
$this->insert('blog::scripts');
$this->end();

$this->push('footer');
$this->insert('data::tag-cloud');
$this->end();
?>
<div class="single-entry h-entry container col offset-md-2"><div class="row">
    <aside class="col-md-2 d-none d-sm-block sidebar blog">
        <p>
            Written on <time class="dt-published" datetime="<?= $this->formatDateRfc($post->created) ?>"><?= $this->formatDate($post->created) ?></time>.
            <?php if ($post->updated) : ?>
            <br />Last updated on <time class="dt-updated" datetime="<?= $this->formatDateRfc($post->updated) ?>"><?= $this->formatDate($post->updated) ?></time>.
            <?php endif ?>
        </p>

        <ul class="tags">
        <?php foreach ($this->processTags($post->tags) as $tag) : ?>
            <li><a class="p-category" href="<?= $tag->link ?>"><?= $tag->name ?></a>
        <?php endforeach ?>
        </ul>
    </aside>

    <article class="col-md-6 blog">
        <h2 class="p-name"><a class="u-url u-uid" href="<?= $this->postUrl($post) ?>"><?= $this->escapeHtml($post->title) ?></a></h2>

        <div class="e-content">
        <?= $post->body ?>

        <?= $post->extended ?>
        </div>

        <div class="p-author h-card d-none">
          Posted by <a class="p-name u-url" href="<?= $this->serverurl() ?>">Matthew Weier O'Phinney</a>,
          <img class="u-photo photo" width="50" src="https://avatars0.githubusercontent.com/u/25943?v=3&u=79dd2ea1d4d8855944715d09ee4c86215027fa80&s=140" alt="mwop">
        </div>

        <div class="divider"></div>

        <div id="disqus_thread"
          data-developer="<?= $disqus['developer'] ?>"
          data-url="<?= $this->serverurl($this->postUrl($post)) ?>"
          data-identifier="<?= $post->id ?>"
          data-title="<?= $post->title ?>"
          data-key="<?= $disqus['key'] ?>"></div>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
    </article>
</div></div>
