<?php
$this->layout('layout::layout', [
    'title'  => $this->escapeHtml($post->title),
    'layout' => 'large',
]);

$pageUrl = $this->serverurl($this->postUrl($post));

$imageAltText = null === $post->image
    ? 'mwop.net celtic knot logo'
    : sprintf(
        "'%s' by %s; licensed under %s",
        $post->image->title,
        $post->image->creator,
        strtoupper($post->image->license),
    );

$this->push('links');
?>
    <!-- OpenGraph -->
    <link rel="canonical" href="<?= $pageUrl ?>" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:creator" content="@mwop" />
    <meta property="og:site_name" content="mwop.net" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<?= $this->escapeHtmlAttr($post->title) ?>" />
    <meta property="og:url" content="<?= $pageUrl ?>" />
    <meta property="og:image" content="<?= $post->image ? $post->image->url : $this->serverurl('/images/logo.png') ?>" />
    <meta property="og:image:alt" content="<?= $this->escapeHtmlAttr($imageAltText) ?>" />
    <meta property="article:published_time" content="<?= $post->created->format('c') ?>" />
    <meta property="article:modified_time" content="<?= $post->updated->format('c') ?>" />
    <?php foreach ($post->tags as $tag): ?>
    <meta property="article:tag" content="<?= $this->escapeHtmlAttr($tag) ?>" />
    <?php endforeach ?>
<?php foreach ($this->processTags($post->tags) as $tag): ?>
    <!-- Feeds -->
    <link href="<?= $this->serverurl($tag->rss) ?>" rel="alternate" type="application/rss+xml" title="mwop.net RSS Feed for <?= $tag->name ?>">
    <link href="<?= $this->serverurl($tag->atom) ?>" rel="alternate" type="application/rss+xml" title="mwop.net RSS Feed for <?= $tag->name ?>">
<?php endforeach; ?>
<?php
$this->end();

$this->push('scripts');
echo '<script src="/assets/js/prism.js"></script>';
echo '<script src="/assets/js/disqus.js"></script>';
$this->end();

$this->push('footer');
$this->insert('data::tag-cloud');
$this->end();
?>
<div class="lg:flex lg:flex-row-reverse lg:justify-end lg:justify-items-start lg:content-start lg:items-start lg:gap-8 h-entry">
    <article class="lg:w-3/4 text-xl">
    <?php if (null === $post->image) : ?>
        <h2 class="p-name"><a class="no-underline text-mwop-fg u-url u-uid" href="<?= $this->postUrl($post) ?>"><?= $this->escapeHtml($post->title) ?></a></h2>
    <?php else : ?>
        <?php /* <section class="float-right ml-4 mb-2 relative"> */ ?>
        <section class="mb-2 lg:float-right lg:w-1/2 lg:ml-4 lg:relative">
            <img class="w-fit h-auto lg:w-full" src="<?= $post->image->url ?>" alt="<?= $post->image->title ?>">
            <h2 class="lg:absolute lg:bottom-4 lg:left-2 p-name"><a class="no-underline text-mwop-fg drop-shadow-lg u-url u-uid" href="<?= $this->postUrl($post) ?>"><?= $this->escapeHtml($post->title) ?></a></h2>
        </section>
    <?php endif ; ?>

        <div class="e-content">
        <?= $post->body ?>

        <?= $post->extended ?>
        </div>

        <div class="hidden p-author h-card">
          Posted by <a class="p-name u-url" href="<?= $this->serverurl() ?>">Matthew Weier O'Phinney</a>,
          <img class="u-photo photo" width="50" src="https://avatars0.githubusercontent.com/u/25943?v=3&u=79dd2ea1d4d8855944715d09ee4c86215027fa80&s=140" alt="mwop">
        </div>

        <p class="my-4 py-4 border-y border-dashed text-center">
            <a href="https://twitter.com/intent/tweet?url=<?= $pageUrl ?>&text=<?= $this->escapeHtmlAttr($post->title) ?>"><i class="fa-brands fa-twitter fa-2xl"></i></a>
            <a href="https://www.facebook.com/sharer.php?u=<?= $pageUrl ?>"><i class="fa-brands fa-facebook fa-2xl"></i></a>
            <a href="https://www.linkedin.com/shareArticle?mini=true&url=<?= $pageUrl ?>"><i class="fa-brands fa-linkedin fa-2xl"></i></a>
        </p>

        <div id="disqus_thread"
          data-developer="<?= $disqus['developer'] ?>"
          data-url="<?= $this->serverurl($this->postUrl($post)) ?>"
          data-identifier="<?= $post->id ?>"
          data-title="<?= $post->title ?>"
          data-key="<?= $disqus['key'] ?>"></div>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
    </article>

    <aside class="w-full md:w-1/4 mb-8 py-4 border-y border-dotted my-4 md:mb-0 md:border-none">
        <p>
            Written on <time class="dt-published" datetime="<?= $this->formatDateRfc($post->created) ?>"><?= $this->formatDate($post->created) ?></time>.
            <?php if ($post->updated) : ?>
            <br />Last updated on <time class="dt-updated" datetime="<?= $this->formatDateRfc($post->updated) ?>"><?= $this->formatDate($post->updated) ?></time>.
            <?php endif ?>
        </p>

        <ul"tags">
        <?php foreach ($this->processTags($post->tags) as $tag) : ?>
            <li><a class="p-category" href="<?= $tag->link ?>"><?= $tag->name ?></a>
        <?php endforeach ?>
        </ul>

    <?php if (null !== $post->image) : ?>
        <p>
            Image by <a href="<?= $post->image->creditUrl ?>"><?= $post->image->creator ?></a>,
            licensed under <a href="<?=$post->image->licenseUrl ?>"><?= strtoupper($post->image->license) ?></a>
        </p>
    <?php endif ?>
    </aside>
</div>
