<?php
$this->render('blog/assets');
$entry = $this->entry;
$title = $entry->getTitle();
$this->headTitle()->prepend($title);
$title = $this->escapeHtml($title);
$url   = $this->url('phly-blog/entry', array('id' => $entry->getId()));
$ds    = function($ts) use ($entry) {
    $tz   = $entry->getTimezone();
    $date = new \DateTime();
    $date->setTimezone(new \DateTimeZone($tz));
    $date->setTimestamp($ts);
    return $date->format('d F Y');
};
foreach ($this->headTitle() as $blogTitle) {}
$this->headLink(array(
    'href'  => $this->url('phly-blog/feed-atom'),
    'type'  => 'application/atom+xml',
    'rel'   => 'alternate',
    'title' => $blogTitle . ' Atom Feed',
));
$this->headLink(array(
    'href'  => $this->url('phly-blog/feed-rss'),
    'type'  => 'application/rss+xml',
    'rel'   => 'alternate',
    'title' => $blogTitle . ' RSS Feed',
));
?>
<div class="row">
<aside class="four columns offset-by-one alpha sidebar blog">
    <p>
        Written on <?php echo $ds($entry->getCreated()) ?>.
        <?php if ($entry->getCreated() < $entry->getUpdated()): ?>
        <br />Last updated on <?php echo $ds($entry->getUpdated()) ?>.
        <?php endif ?>
    </p>

    <?php echo $this->render('blog/tags', array('tags' => $entry->getTags())) ?>

</aside>

<article class="eleven columns omega blog">
<h2><?php echo $title ?></h2>
<?php
echo $entry->getBody();
echo $entry->getExtended();
echo $this->render('blog/social-media');
echo $this->disqus($entry->getId(), $url, $title);
?>
</article>

