<?php 
$entry = $this->entry; 
$ds    = function($ts) use ($entry) {
    $tz   = $entry->getTimezone();
    $date = new \DateTime();
    $date->setTimezone(new \DateTimeZone($tz));
    $date->setTimestamp($ts);
    return $date->format('d F Y');
};
$url      = $this->plugin('url');
$entryUrl = $url('phly-blog/entry', array('id' => $entry->getId()));
$title    = $this->escapeHtml($entry->getTitle());
?>
<aside class="four columns offset-by-one alpha sidebar blog">
    <p>
        Written on <?php echo $ds($entry->getCreated()) ?>.
        <?php if ($entry->getCreated() < $entry->getUpdated()): ?>
        <br />Last updated on <?php echo $ds($entry->getUpdated()) ?>.
        <?php endif ?>
    </p>

    <?php echo $this->render('blog/tags', array('tags' => $entry->getTags())) ?>

</aside>

<section class="eleven columns omega">
    <h4 class="entry"><a href="<?php echo $entryUrl ?>"><?php echo $title ?></a></h4>

    <div class="entry body"><?php echo $entry->getBody() ?></div>

    <p><a href="<?php echo $entryUrl ?>">Continue reading...</a></p>
</section>

