<?php
$tags         = $this->tags;
$url          = $this->plugin('url');
$renderedTags = array();

foreach ($tags as $tag) {
    $tagForUrl = str_replace(array(' ', '%20'), '+', $tag);
    $renderedTags[] = sprintf(
        '<a href="%s">%s</a>', 
        $url('phly-blog/tag/page', array('tag' => $tagForUrl)),
        $tag
    );
}
echo "<ul class=\"tags\">\n    <li>", implode("</li>\n    <li>", $renderedTags), "</li>\n</ul>\n";
