<?php 
$paginatorUrl = $this->paginator_url;
$this->headTitle()->prepend($this->title);
$this->headLink(array(
    'href'  => $paginatorUrl . '.xml',
    'type'  => 'application/atom+xml',
    'rel'   => 'alternate',
    'title' => $this->title . ' Atom Feed',
));
$this->headLink(array(
    'href'  => $paginatorUrl . '.xml?type=rss',
    'type'  => 'application/rss+xml',
    'rel'   => 'alternate',
    'title' => $this->title . ' RSS Feed',
));
?>
<div class="row">
<div class="eleven columns alpha blog">
    <h2><?php echo $this->title ?></h2>

<?php 
$entries = $this->entries;
foreach ($entries as $entry) {
    echo '<div class="row clearfix">', "\n";
    echo $this->render('blog-entry/entry-short.phtml', array('entry' => $entry));
    echo '</div>', "\n";
}

echo $this->paginationControl($entries, 'Sliding', 'blog-entry/paginator.phtml', array('url' => $paginatorUrl));
?>
</div>

<div class="four columns offset-by-one omega sidebar blog">
    <?php echo $this->render('blog-entry/blogroll.phtml') ?>
</div>
</div>
