<?php $this->headTitle()->prepend('Unauthorized') ?>
<section class="code_401">
<h2>Unauthorized</h2>

<p>
    You are not logged in, and therefore cannot perform this action.
</p>

<p>
<?php
$url = $this->url('zfcuser/login');
if (isset($this->redirect) && !empty($this->redirect)) {
    $url .= '?redirect=' . $this->redirect;
}
?>
    <a href="<?php echo $url ?>">Login to continue.</a>
</p>
</section>
