<?php
$this->headScript()->appendScript('require(["Application/tweets"]);')
?>
<article class="one-third column alpha home">
<h2>Welcome!</h2>

<p>
    I'm Matthew Weier O'Phinney. I am:
</p>

<ul>
    <li>A husband.</li>
    <li>A father of two wonderful children.</li>
    <li>A Basset Hound, well, owner's not the right word. Our
        <?php
        $birthday = new \DateTime('2011-03-01');
        $today    = new \DateTime();
        $interval = $today->diff($birthday);
        ?>
        <?php echo $interval->format('%y') ?>-year, 
        <?php echo $interval->format('%m') ?>-month-old Basset likely thinks I'm a toy to chew on.</li>
    <li>A <a href="http://php.net">PHP</a> developer and framework architect.</li>
    <li>A frequent PHP conference speaker.</li>
    <li>An open source software developer and advocate.</li>
    <li>A (sometimes) brewer of beer.</li>
</ul>

<p>
    I <a href="blog">blog</a> reasonably regularly, typically on topics related
    to open source development. Feel free to <a href="contact">contact me</a>.
</p>
</article>

<aside class="one-third column middle home">
    <img src="http://farm4.staticflickr.com/3315/3625794227_8d038eac5e_n.jpg" alt="Portrait by Rob Allen" /><br />
    <em>Photo &copy; All rights reserved by <a href="http://www.flickr.com/photos/akrabat/">Rob Allen</a></em>
</aside>

<aside class="one-third column omega home">
    <?php echo $this->render('github-links'); ?>

    <h3>Recent Tweets</h3>
    <ul id="tweets"></ul>
    <p><em><a href="http://twitter.com/weierophinney">View more tweets</a></em></p>
</aside>

