<article class="five columns alpha home">
<h2>Welcome!</h2>

<p>
    I'm Matthew Weier O'Phinney. I am:
</p>

<ul>
    <li>A husband.</li>
    <li>A father of two wonderful children.</li>
    <li>A <a href="http://php.net">PHP</a> developer and framework architect.</li>
    <li>A frequent PHP conference speaker.</li>
    <li>An open source software developer and advocate.</li>
    <li>A (sometimes) brewer of beer.</li>
    <li>A (budding) fitness junkie.</li>
</ul>

<p>
    I <a href="/blog.html">blog</a> reasonably regularly, typically on topics related
    to open source development. Feel free to <a href="contact">contact me</a>.
</p>
</article>

<aside class="four columns middle home">
    <img src="http://farm4.staticflickr.com/3315/3625794227_8d038eac5e_n.jpg" alt="Portrait by Rob Allen" /><br />
    <em>Photo &copy; All rights reserved by <a href="http://www.flickr.com/photos/akrabat/">Rob Allen</a></em>
</aside>

<aside class="six columns omega home">
    <?php 
        $this->headScript()->appendScript('require(["Application/githublinks"], function(links) {});');
        echo $this->render('github'); 
    ?>

    <a class="twitter-timeline" href="https://twitter.com/mwop" data-widget-id="269876420560420864">Tweets by @mwop</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

</aside>

