<?php $this->headTitle()->prepend('R&eacute;sum&eacute;') ?>
<article class="resume">
<section>
<h2>Personal Statement</h2> 

<p> 
    I am an open source software architect, specializing in PHP.
</p> 

<p> 
    I am currently project lead for <a href="http://framework.zend.com/">Zend
        Framework</a>, a project with which I have been involved since before 
    the first public preview release. I am a Zend Certified Engineer, and a 
    member of the Zend Education Advisory Board, the group responsible for 
    authoring the Zend Certification Exam. I contribute to a number of open 
    source projects, blog on PHP-related topics, and present talks and tutorials 
    related to PHP development and the projects to which I contribute.
</p> 
</section>
 
<section>
<h3><a name="work">Selected Work Experience</a></h3> 

<dl class="resume">
    <dt><a href="http://www.zend.com/">Zend Technologies, Inc.</a></dt>
    <dd>
        <p class="metadata">
            Project Lead, Zend Framework<br />
            April 2009 &#8212; Present
        </p>

        <p>
            Duties include scoping Zend Framework releases; interfacing with
            Zend customers and partners; acting as community liaison; creating
            architecture guidelines for the project; and more.
        </p>
    </dd>

    <dt><a href="http://www.zend.com/">Zend Technologies, Inc.</a></dt>
    <dd>
        <p class="metadata">
            Software Architect, Zend Framework<br />
            April 2008 &#8212; April 2009
        </p>

        <p>
            Duties included acting as community liaison; creating
            architecture guidelines for the project; driving component creation
            on several initiatives, including Dojo integration; and more.
        </p>
    </dd>

    <dt><a href="http://www.zend.com/">Zend Technologies, Inc.</a></dt>
    <dd>
        <p class="metadata">
            PHP Developer <br />
            September 2005 &#8212; April 2008
        </p>

        <p>
            Duties included maintenance and development of public-facing company
            websites; creation and maintenance of middle-tier web service layer
            used by public websites and internal processes; site architecture
            and team development; contribution to Zend Framework; and more.
        </p>
    </dd> 
    
    <dt><a href="http://www.garden.org">National Gardening Association</a></dt> 
    <dd>
        <p class="metadata"> 
            Webmaster and IT Specialist<br /> 
            August 2003 &#8212; September 2005
        </p> 

        <p> 
            Duties included development and maintenance of NGA web properties;
            systems administration of both public and internal network
            infrastructure, including LVS-HA web/database cluster, bulk mail
            system, and company email server. 
        </p> 
    </dd> 
    
    <dt>Freelance Consultant</dt>
    <dd>
        <p class="metadata">January 2002 &#8212; January 2009</p> 

        <p> 
            Projects required installation and utilization of both development
            and customer test web servers, backup policies (utilizing both CVS
            for versioning and removable media for physical backups), domain
            registration, and setting up a Linux-based firewall, router,
            gateway, and server. Clients included private sector businesses,
            educational institutions, not-for-profit agencies, and open source
            projects.
        </p> 
    </dd> 
    
    <dt><a href="http://www.zootweb.com">Zoot Enterprises, Inc.</a></dt>
    <dd>
        <p class="metadata">
            Web Applications Programmer<br/> 
            February 2001 &#8212; October 2002
        </p> 
        <p> 
            Worked in-house from February through mid-June 2001 as web
            applications programmer, primarily on online credit and loan
            applications.
        </p> 
    </dd> 
</dl> 
</section>

<section>
<h3><a name="talks">Presentations</a></h3> 

<p>
    I've been speaking at PHP-related conferences and user groups since October
    2005, as well as performing online webinars, participating in podcasts, and
    more. I've delivered several dozen presentations, most of which are
    available via <a href="http://slideshare.net/weierophinney">my SlideShare
    account</a>. Below are a few select presentations.
</p>
 
<dl class="resume">
    <dt><a href="/slides/2011-10-18-Zf2-Overview/Zf2Overview.html">Zend Framework 2.0 - Overview</a></dt>
    <dd>
        <p class="metadata">
            Zend Conference and Exposition<br />
            October 2011
        </p>

        <p>
            <a href="http://www.youtube.com/watch?v=T0LMaODppcc&feature=youtu.be">View the recorded talk.</a>
        </p>
    </dd>

    <dt><a href="/slides/2011-05-26-BeautifulSoftware.pdf">Designing Beautiful Software</a></dt>
    <dd>
        <p>
            php|tek<br />
            May 2011
        </p>
    </dd>

    <dt>Zend Framework Workshop</dt>
    <dd>
        <p class="metadata">
            Delivered with <a href="http://akrabat.com/">Rob Allen</a><br />
            Dutch PHP Conference<br />
            June 2010
        </p>

        <div style="width:425px" id="__ss_4480868"> <strong style="display:block;margin:12px 0 4px"><a href="http://www.slideshare.net/weierophinney/zend-framework-workshop-4480868" title="Zend Framework Workshop">Zend Framework Workshop</a></strong> <iframe src="http://www.slideshare.net/slideshow/embed_code/4480868" width="425" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe> <div style="padding:5px 0 12px"> View more <a href="http://www.slideshare.net/">presentations</a> from <a href="http://www.slideshare.net/weierophinney">Matthew Weier O'Phinney</a></div></div>
    </dd>
</dl> 
</section>
 
<section>
<h3><a name="articles">Publications</a></h3> 
 
<dl class="resume">
    <dt>Real-World Solutions for Developing High-Quality PHP Frameworks and Applications</dt>
    <dd>
        <p class="metadata">
            edited by Sebastian Bergmann and Stefan Priebsch<br />
            December 2010, Hanser (German edition)<br />
            May 2011, Wrox (English edition)
        </p>

        <p>
            Contributed a case study entitled "Testing Service Oriented APIs",
            detailing unit testing and integration testing approaches for web
            services, using approaches learned in testing Zend Framework.
        </p>
    </dd>

    <dt><a href="http://www.phparch.com/magazine/2009-2/september/">php|architect: Lifecyle of a Bug</a></dt>
    <dd>
        <p class="metadata">September 2009</p>
    </dd>

    <dt><a href="http://www.phparch.com/magazine/2009-2/june/">php|architect:
        Zend Framework</a></dt>
    <dd>
        <p class="metadata">June 2009</p>
    </dd>

    <dt><a href="http://www.phparch.com/magazine/2009-2/february/">php|architect: Optimizing Dojo and Zend Framework Integration</a></dt>
    <dd>
        <p class="metadata">
            February 2009
        </p>
    </dd>

    <dt>The PHP Anthology: 101 Essential Tips, Tricks & Hacks,  2nd Edition</i></dt> 
    <dd>
        <p class="metadata"> 
            with Ben Balbo, Harry Fuecks, Davey Shafik, and Ligaya Turmelle<br /> 
            October, 2007<br /> 
            SitePoint Pty, Ltd, Australia
        </p> 

        <p> 
            Contributed three chapters to this edition, including Chapter 3,
            "Error Handling"; Chapter 12, "XML and Web Services"; and Chapter
            13, "Best Practices".
        </p> 
    </dd> 
</dl> 
</section>
 
<section>
<h3><a name="oss">Open Source Contributions</a></h3> 
 
<dl class="resume">
    <dt><a href="http://ohloh.net/accounts/weierophinney">OhLoh</a></dt>
    <dd>
        Overview of a number of OSS projects to which I contribute.
    </dd>

    <dt><a href="http://resume.github.com/?weierophinney">GitHub</a></dt>
    <dd>
        Contributions made via <a href="http://github.com/">GitHub</a>.
    </dd>

    <dt><a href="http://framework.zend.com/">Zend Framework</a></dt>
    <dd>
        Contributions have been made since January 2006:

        <ul>
            <li>From January 2006 &emdash; April 2008, as PHP Developer for
                Zend Technologies</li>
            <li>From April 2008 &emdash; March 2009, as Software Architect for
                Zend Framework</li>
            <li>From April 2009 &emdash; Present, as Project Lead for
                Zend Framework</li>
        </ul>
    </dd>

    <dt><a href="http://pear.php.net/">PEAR</a></dt> 
    <dd>
        <p class="metadata"> 
            July 13, 2005 &#8212; Present
        </p> 

        <p> 
            Lead maintainer for <a href="http://pear.php.net/packages/File_Fortune">File_Fortune</a>.
        </p> 
    </dd> 
    
    <dt><a href="http://solarphp.com">Solar Framework</a>
    <dd> 
        <p class="metadata"> 
            July 2005 &#8212; December 2005
        </p> 

        <p> 
            Collaboration with <a href="http://paul-m-jones.com/blog/">Paul M. Jones</a> 
            on form validation routines.
        </p> 
    </dd> 
    
    <dt><a href="http://cgiapp.sourceforge.net/">Cgiapp</a></dt>
    <dd> 
        <p class="metadata"> 
            March 2004 &#8212; March 2006
        </p> 

        <p> 
            PHP port of the perl module CGI::Application.
        </p> 
    </dd> 
</dl> 
</section>
</article>

