<?php if ($this->error): ?>
<p class="error"><?php echo $this->error ?></p>
<?php 
    return;
endif;

$entry = $this->entry;
$title = $entry->getTitle();
$this->headTitle()->prepend($title);
$title = $this->vars()->escape($title);
$url   = $this->url(array('id' => $entry->getId()), array('name' => 'blog/entry'));
$ds    = function($ts) use ($entry) {
    $tz   = $entry->getTimezone();
    $date = new \DateTime();
    $date->setTimezone(new \DateTimeZone($tz));
    $date->setTimestamp($ts);
    return $date->format('Y-m-d H:i:s');
};
?>
<div class="row">
<article class="eleven columns alpha blog">
<?php if ($this->entry_updated): ?>
<h2 class="notification">Entry updated</h2>
<?php endif ?>
<h2><?php echo $title ?></h2>
<?php
echo $entry->getBody();
echo $entry->getExtended();
echo $this->disqus($entry->getId(), $url, $title);
?>
</article>

<aside class="four columns offset-by-one omega sidebar blog">
    <div class="metadata">
        <ul>
            <li>Posted on <b><?php echo $ds($entry->getCreated()) ?></b>.</li>
            <li>Last updated on <b><?php echo $ds($entry->getUpdated()) ?></b>.</li>
        </ul>
    </div>

    <div class="metadata">
        <h4>Tags for this entry</h4>
        <p class="tags"><?php echo $this->render('blog-entry/tags.phtml', array('tags' => $entry->getTags())) ?></p>
    </div>

    <?php echo $this->render('blog-entry/blogroll.phtml') ?>
</aside>

