<?php $errors = $this->errors; ?>
<div class="ten columns admin">
<h2>Create blog entry</h2>
<form class="blog" action="<?php echo $this->url ?>" method="post">
<dl>
    <dt><label for="title">Title</label></dt>
    <dd>
        <input name="title" type="text" value="" />
        <?php if ($errors && isset($errors['title'])):
            foreach ($errors['title'] as $message):
                printf("<li>%s</li>\n", $message);
            endforeach;
        endif; ?>
    </dd>

    <dt><label for="author">Author</label></dt>
    <dd>
        <input name="author" type="text" value="" />
        <?php if ($errors && isset($errors['author'])):
            foreach ($errors['author'] as $message):
                printf("<li>%s</li>\n", $message);
            endforeach;
        endif; ?>
    </dd>

    <dt><label for="body">Content</label></dt>
    <dd>
        <textarea name="body"></textarea>
        <?php if ($errors && isset($errors['body'])):
            foreach ($errors['body'] as $message):
                printf("<li>%s</li>\n", $message);
            endforeach;
        endif; ?>
    </dd>

    <dt><label for="extended">Extended Content</label></dt>
    <dd>
        <textarea name="extended"></textarea>
        <?php if ($errors && isset($errors['extended'])):
            foreach ($errors['extended'] as $message):
                printf("<li>%s</li>\n", $message);
            endforeach;
        endif; ?>
    </dd>
</dl>
<input name="save" type="submit" value="Save" />
</form>
</div>

<div class="five columns offset-by-one admin sidebar">
    <h4>Admin Sidebar</h4>
</div>

