<?php 
$entry = $this->entry;
$title = $entry->getTitle();
$this->headTitle()->prepend($title);
$title = $this->escape($title);
$url   = $this->url('phly-blog/entry', array('id' => $entry->getId()));
$ds    = function($ts) use ($entry) {
    $tz   = $entry->getTimezone();
    $date = new \DateTime();
    $date->setTimezone(new \DateTimeZone($tz));
    $date->setTimestamp($ts);
    return $date->format('Y-m-d H:i:s');
};
foreach ($this->headTitle() as $blogTitle) {}
$this->headLink(array(
    'href'  => $this->url('phly-blog/feed-atom'),
    'type'  => 'application/atom+xml',
    'rel'   => 'alternate',
    'title' => $blogTitle . ' Atom Feed',
));
$this->headLink(array(
    'href'  => $this->url('phly-blog/feed-rss'),
    'type'  => 'application/rss+xml',
    'rel'   => 'alternate',
    'title' => $blogTitle . ' RSS Feed',
));
?>
<article class="blog">
<h2><?php echo $title ?></h2>
<?php
echo $entry->getBody();
echo $entry->getExtended();
?>
</article>

<aside class="sidebar blog">
    <div class="metadata">
        <ul>
            <li>Posted on <b><?php echo $ds($entry->getCreated()) ?></b>.</li>
            <li>Last updated on <b><?php echo $ds($entry->getUpdated()) ?></b>.</li>
        </ul>
    </div>

    <div class="metadata">
        <h4>Tags for this entry</h4>
        <p class="tags"><?php echo $this->render('blog/tags', array('tags' => $entry->getTags())) ?></p>
    </div>
</aside>

