<?php 
$entry = $this->entry; 
$ds    = function($ts) use ($entry) {
    $tz   = $entry->getTimezone();
    $date = new \DateTime();
    $date->setTimezone(new \DateTimeZone($tz));
    $date->setTimestamp($ts);
    return $date->format('Y-m-d H:i:s');
};
$url      = $this->plugin('url');
$entryUrl = $url('phly-blog/entry', array('id' => $entry->getId()));
$title    = $this->escape($entry->getTitle());
?>
<aside class="entry meta">
    <p class="date"><?php echo $ds($entry->getCreated()) ?></p>
    <p class="tags"><?php echo $this->render('phly-blog/tags', array('tags' => $entry->getTags()))?></p>
</aside>

<section class="entry">
    <h4><a href="<?php echo $entryUrl ?>"><?php echo $title ?></a></h4>

    <div class="body"><?php echo $entry->getBody() ?></div>

    <p><a href="<?php echo $entryUrl ?>">Continue reading...</a></p>
</section>

