run "cp #{shared_path}/appconfig/*.php #{release_path}/config/autoload/"
run "ln -nfs #{shared_path}/users.db #{release_path}/data/users.db"
sudo "chmod -R a+rwX #{release_path}/data"
run "cd #{release_path} && /usr/bin/php public/index.php githubfeed fetch"
run "cd #{release_path} && /usr/bin/php public/index.php phlycomic fetch all"
run "cd #{release_path} && /usr/bin/php public/index.php phlysimplepage cache clear all"
