<?php 
$entry = $this->vars('entry'); 
$ds    = function($ts) use ($entry) {
    $tz = $entry->getTimezone();
    $date = new \DateTime();
    $date->setTimezone(new \DateTimeZone($tz));
    $date->setTimestamp($ts);
    return $date->format('Y-m-d H:i:s');
};
$url      = $this->plugin('url');
$entryUrl = $url->direct(array('id' => $entry->getId()), array('name' => 'blog-entry'));
$title    = $this->vars()->escape($entry->getTitle());
?>
<div class="grid_2 entry meta">
    <p class="tags"><?php echo $this->render('blog/tags.phtml', array('tags' => $entry->getTags()))?></p>
    <p class="date"><?php echo $ds($entry->getCreated()) ?></p>
</div>
<div class="grid_6">
    <h4 class="entry"><a href="<?php echo $entryUrl ?>"><?php echo $title ?></a></h4>

    <div class="entry body"><?php echo $entry->getBody() ?></div>

    <p><a href="<?php echo $entryUrl ?>">Continue reading...</a></p>
</div>
<div class="clear"></div>

