<?php 
$paginatorUrl = $this->paginator_url;
$this->headTitle()->prepend($this->title) ?>
<div class="grid_9 content blog">
    <h2><?php echo $this->title ?></h2>

<?php 
$entries = $this->entries;
foreach ($entries as $entry) {
    echo $this->render('blog/entry-short.phtml', array('entry' => $entry));
}

echo $this->paginationControl($entries, 'Sliding', 'blog/paginator.phtml', array('url' => $paginatorUrl));
?>
</div>

<div class="grid_3 sidebar blog">
    <?php echo $this->render('blog/blogroll.phtml') ?>
</div>

