<?php $this->layout('layout::layout', [
    'title'  => 'Admin',
    'layout' => 'small',
]) ?>
<section class="flex flex-row justify-items-center">
    <div class="bg-mwop-nav p-4 w-full">
        <h4>Admin</h4>

        <div class="bg-mwop-bg gap-4 divide-y divide-mwop-dark divide-solid">
            <a class="block p-2" href="<?= $this->url('comics') ?>">View comics</a>
            <a class="block p-2" href="<?= $this->url('admin.fetch-comics') ?>">Fetch comics</a>
            <a class="block p-2" href="<?= $this->url('art.photo.upload') ?>">Upload photo</a>
            <a class="block p-2" href="<?= $this->url('admin.clear-response-cache') ?>">Clear response cache</a>
        </ul>
    </div>
</section>
