<?php $this->layout('layout::layout', [
    'title' => 'Admin',
]) ?>
<section class="admin col-md-6">
    <div class="card">
        <div class="card-header">
            <h4>Admin</h4>
        </div>

        <ul class="list-group list-group-flush">
            <li class="list-group-item"><a href="<?= $this->url('comics') ?>">View comics</a></li>
            <li class="list-group-item"><a href="<?= $this->url('art.photo.upload') ?>">Upload photo</a></li>
        </ul>
    </div>
</section>
