<?php $this->layout('layout::layout', [
    'title' => 'Admin',
]) ?>
<section class="w-1/3 mt-24 mx-auto flex flex-row justify-items-center">
    <div class="bg-neutral-700 p-4 w-full">
        <h4>Admin</h4>

        <div class="bg-neutral-800 gap-4 divide-y divide-neutral-500 divide-solid">
            <a class="block p-2" href="<?= $this->url('comics') ?>">View comics</a>
            <a class="block p-2" href="<?= $this->url('art.photo.upload') ?>">Upload photo</a>
            <a class="block p-2" href="<?= $this->url('admin.clear-response-cache') ?>">Clear response cache</a>
        </ul>
    </div>
</section>
