<?php $this->layout('layout::layout', [
    'title' => 'Comics',
]) ?>
<?php $this->push('scripts'); ?>
<script src="/assets/js/imagesloaded.pkgd.min.js"></script>
<script src="/assets/js/masonry.pkgd.min.js"></script>
<script>
(function() {
    imagesLoaded(document.querySelector('.comics-grid'), function () {
        new Masonry('.comics-grid', {
            itemSelector: ".comic"
        });
    });
})();
</script>
<?php $this->end(); ?>
<article class="mt-24 mb-4 mx-auto w-11/12 text-center">
    <h2>Comics</h2>

    <div class="comics-grid">
        <?php $this->insert('data::comics') ?>
    </div>
</article>
