<?php $this->layout('layout::layout', [
    'title' => 'Comics',
]) ?>
<div class="mt-24 mb-8">

<article class="mx-auto mt-24 mb-8 w-11/12 text-center">
    <h2>Comics</h2>

    <div class="grid" data-masonry='{ "itemSelector": ".comic" }'>
        <?php $this->insert('data::comics') ?>
    </div>
</article>

</div>
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
