<?php $this->layout('layout::layout', [
    'title' => 'Welcome',
]) ?>
<article class="col-lg alpha home">
    <h2>Welcome!</h2>

    <p>
        I'm Matthew Weier O'Phinney. I am a Principal Engineer, PHP expert, and
        standards developer. I write the tools that PHP developers use to build
        their applications, from APIs to content management systems. In
        addition, I am:
    </p>

    <ul>
        <li>He/him.</li>
        <li>A husband.</li>
        <li>A father of two wonderful children.</li>
        <li>An open source software developer and advocate.</li>
    </ul>

    <p>
        I blog <a href="<?= $this->url('blog') ?>">on this site</a>, as well as elsewhere (see the
        icons next to the "Recent Blog Posts"), typically on topics related
        to open source development. Feel free to <a href="<?= $this->url('contact') ?>">contact me</a>.
    </p>
</article>

<aside class="col-lg middle home">
    <img src="/images/2018-09-09-mwop-nugget-320x420.jpg" alt="Matthew likes puppers" /><br />
</aside>

<aside class="col-lg omega home">
    <h3>Recent Blog Posts</h3>

    <ul>
    <?php foreach ($posts as $post) : ?>
      <li><a href="<?= $post['siteurl'] ?>"><img
        src="<?= $post['favicon'] ?>"
        alt="<?= $this->escapeHtmlAttr($post['sitename']) ?>"
        title="<?= $this->escapeHtmlAttr($post['sitename']) ?>"
        width="16"></a>&nbsp;<a href="<?= $post['link'] ?>"><?= $this->escapeHtml($post['title']) ?></a></li>
    <?php endforeach ?>
    </ul>

    <p><em><a href="<?= $this->url('blog') ?>">Read more</a></em></p>

    <h3>Recent Github Activity</h3>

    <ul id="github">
        <?php $this->insert('data::github-links') ?>
    </ul>

    <p><em><a href="https://github.com/weierophinney?tab=activity">Read more</a></em></p>

    <a class="twitter-timeline" href="https://twitter.com/mwop" data-widget-id="269876420560420864">Tweets by @mwop</a>
    <script src="/js/twitter.js"></script>
</aside>

<div class="h-card vcard d-none">
  <img class="u-photo photo" width="50" src="https://avatars0.githubusercontent.com/u/25943?v=3&u=79dd2ea1d4d8855944715d09ee4c86215027fa80&s=140" alt="mwop">,
  <a class="p-name fn u-url url" href="<?= $this->serverurl() ?>" rel="me">Matthew Weier O'Phinney</a>,
  <a class="u-email email" href="mailto:matthew@weierophinney.net">matthew@weierophinney.net</a>,
  <span class="p-nickname nickname">mwop,weierophinney</span>,
  <div class="p-note note">
    <p>
      <a href="<?= $this->serverurl() ?>" rel="author">Matthew Weier O'Phinney</a> is a
        Principal Engineer, PHP expert, and
        standards developer. He writes tools that PHP developers use to build
        their applications, from APIs to content management systems, including Zend Framework, Apigility, and Expressive.
        He is a renowned speaker and technical writer, blogs at
        <a href="<?= $this->serverurl($this->url('blog')) ?>"><?= $this->serverurl($this->url('blog')) ?></a>
        and tweets as <a href="https://twitter.com/mwop">@mwop</a>.
    </p>
  </div>
</div>
