<?php $this->layout('layout::layout', [
    'title'  => 'Login',
    'layout' => 'small',
]) ?>
<section class="flex flex-row justify-items-center">
    <div class="bg-mwop-nav p-4 w-full rounded-lg">
        <h2>Login</h2>

        <?php if (isset($error)) : ?>
        <p class="my-4 text-red-700 font-bold">
            Unable to validate your credentials. Please try again.
        </p>
        <?php endif ?>

        <form class="" method="post" name="login" action="<?= $this->url('login') ?>" id="login">
            <div class="form-group">
                <label class="block mb-2 font-semibold" for="username">Username:</label>
                <input class="w-full mb-4 p-2 rounded border-mwop-bg bg-mwop-fg text-mwop-bg" type="text" name="username" value="" placeholder="Enter your username" required="required">
            </div>

            <div class="form-group">
                <label class="block mb-2 font-semibold" for="password">Subject:</label>
                <input class="w-full mb-4 p-2 rounded border-mwop-bg bg-mwop-fg text-mwop-bg" type="password" name="password" value="" placeholder="Provide your password" required="required">
            </div>

            <button class="rounded p-2 bg-action-bg border-action-border text-mwop-bg hover:bg-action-active active:bg-action-active transition duration-300" type="submit" name="login">Login</button>
        </form>
    </div>
</section>
