<div class="col-md-8 col-md-offset-2 text-center">
  <ul class="pagination pagination-sm">
    <?php if (! $pagination->is_first) : ?>
    <li><a href="<?= $pagination->base_path ?>" class="first">&lt;&lt;<span class="sr-only">First</span></a></li>
    <?php endif ?>

    <?php if (isset($pagination->previous)) : ?>
    <li><a href="<?= $pagination->base_path ?>?page=<?= $pagination->previous ?>">&lt;<span class="sr-only">Previous</span></a></li>
    <?php endif ?>

    <?php foreach ($pagination->pages as $page) : ?>
        <?php if ($page['current']) : ?>
    <li class="active"><a href="#"><?= $page['number'] ?></a></li>
        <?php else : ?>
    <li><a href="<?= $pagination->base_path ?>?page=<?= $page['number'] ?>"><?= $page['number'] ?></a></li>
        <?php endif ?>
    <?php endforeach ?>

    <?php if (isset($pagination->next)) : ?>
    <li><a href="<?= $pagination->base_path ?>?page=<?= $pagination->next ?>"><span class="sr-only">Next</span>&gt;</a></li>
    <?php endif ?>

    <?php if (! $pagination->is_last) : ?>
    <li><a href="<?= $pagination->base_path ?>?page=<?= $pagination->last ?>" class="last"><span class="sr-only">Last</span>&gt;&gt</a></li>
    <?php endif ?>
  </ul>
</div>
