<?php $this->layout('layout::layout', [
    'title'  => 'R&eacute;sum&eacute;',
    'layout' => 'large',
]) ?>
<section class="w-full mb-8 p-8 rounded-lg bg-mwop-nav text-mwop-fg">
    <h2>Personal Statement</h2> 

    <p> 
        I am a software engineer and architect, PHP expert, standards
        developer, and product manager. I create the tools that PHP
        developers use to build and deploy their applications, from APIs
        to content management systems.
    </p> 

    <p> 
        I am currently project lead for the <a href="https://getlaminas.org">Laminas Project</a>,
        the open source continuation of <a href="https://framework.zend.com/">Zend
        Framework</a>. I began developing on Zend Framework before its
        first public release, and led the project from 2009 through 2019,
        during which time we released two more major versions, and spun off
        the <a href="https://apigility.org">Apigility</a> (now <a href="https://api-tools.getlaminas.org">Laminas API Tools</a>)
        and <a href="https://getexpressive.org">Expressive</a> (now <a href="https://docs.mezzio.dev">Mezzio</a>)
        projects.
    </p>

    <p>
        I am a founding member of the <a href="https://www.php-fig.org/">PHP Framework Interop Group (PHP-FIG)</a>,
        a group creating and promoting standards for the PHP ecosystem. I
        was voted to the inaugural Core Committee, and am currently serving
        my second term in that body.
    </p>

    <p class="mb-2">
        I contribute to a number of open source projects, blog on
        PHP-related topics, and present talks and tutorials related to PHP
        development and the projects to which I contribute.
    </p> 
</section>

<section>
    <h3 class="mb-4" id="work">Selected Work Experience</h3> 

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h4 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://www.perforce.com">Perforce</a></h4>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic">
                Product Manager / Principal Engineer (October 2019 &#8212; Present)
            </p>

            <p>
                My principal role is as the Zend Product Manager, where I oversee
                product development for the Zend brand, including ZendPHP
                and Zend Server. My duties include market research, engineering
                prioritization, sales and support enablement, and marketing content
                development.
            </p>

            <p>
                I also continue in my role as Project Lead of Laminas,
                and in participation with standards groups (specifically
                <a href="https://www.php-fig.org">PHP-FIG</a>).
            </p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h4 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://www.zend.com/">Zend Technologies, Inc.</a><br />
            <span class="text-sm"><a href="https://www.roguewave.com">RogueWave Software</a><br />October 2015 — December 2018<br />
            <a href="https://www.perforce.com">Perforce</a><br />January — June 2019</span></h4>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic">
                Principal Engineer (April 2013 &#8212; June 2019)<br />
                Project Lead, Zend Framework (April 2009 &#8212; June 2019)<br />
                Software Architect, Zend Framework (April 2008 &#8212; April 2009)
            </p>

            <p>
                Duties included scoping Zend Framework, Apigility, and
                Expressive releases; interfacing with Zend customers and
                partners; acting as community liaison; creating architecture
                guidelines for all projects under the Zend Framework
                umbrella; participation with standards groups (specifically
                <a href="https://www.php-fig.org">PHP-FIG</a>); and more.
            </p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h4 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://www.zend.com/">Zend Technologies, Inc.</a></h4>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic">
                PHP Developer <br />
                September 2005 &#8212; April 2008
            </p>

            <p>
                Duties included maintenance and development of public-facing company
                websites; creation and maintenance of middle-tier web service layer
                used by public websites and internal processes; site architecture
                and team development; contribution to Zend Framework; and more.
            </p>
        </div> 
    </div>
        
    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h4 class="w-full lg:w-1/4 mt-4 font-serif"><a href="http://www.garden.org">National Gardening Association</a></h4> 

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic"> 
                Webmaster and IT Specialist<br /> 
                August 2003 &#8212; September 2005
            </p> 

            <p> 
                Duties included development and maintenance of NGA web properties;
                systems administration of both public and internal network
                infrastructure, including LVS-HA web/database cluster, bulk mail
                system, and company email server. 
            </p> 
        </div> 
    </div> 
</section>

<section>
    <h3 id="talks">Presentations</h3> 

    <p>
        I've been speaking at PHP-related conferences and user groups since October
        2005, as well as performing online webinars, participating in podcasts, and
        more. I've spoken at dozens of conferences, delivering well over 100
        presentations. Below are a few select presentations; <a href="/contact">contact me</a>
        if you need a link to a presentation not listed here.
    </p>
    
    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://slides.mwop.net/2018-06-12-Middleware-For-That/">There's a Middleware for That</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p>
                <a href="https://www.meetup.com/mn-php/events/250795278/">Minnesota PHP User Group</a><br />
                12 June 2018
            </p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://slides.mwop.net/2017-10-25-Middleware-Express/">The Middleware Express</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic">
                ZendCon (Keynote)<br />
                October 2017
            </p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://slides.mwop.net/2015-02-07-PHP-Speaks-HTTP/">PHP Speaks HTTP?</a></h5>
        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic">
                PHPBenelux<br />
                February 2015
            </p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://slides.mwop.net/2014-02-25-Apigility/">Apigility</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic">
                PHPBenelux<br />
                January 2014
            </p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://slides.mwop.net/2012-01-28-Vim/VimUnixToolchain.html">Vim + Unix Toolchain == IDE</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p>
                <a href="http://conference.phpbenelux.eu/2012/">PHPBenelux 2012</a><br />
                January 2012
            </p>
        </div>
    </div>
</section>

<section>
    <h3 id="articles">Publications</h3> 
    
    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif">Real-World Solutions for Developing High-Quality PHP Frameworks and Applications</h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic">
                edited by Sebastian Bergmann and Stefan Priebsch<br />
                December 2010, Hanser (German edition)<br />
                May 2011, Wrox (English edition)
            </p>

            <p>
                Contributed a case study entitled "Testing Service Oriented APIs",
                detailing unit testing and integration testing approaches for web
                services, using approaches learned in testing Zend Framework.
            </p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="http://www.phparch.com/magazine/2009-2/september/">php|architect: Lifecyle of a Bug</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic">September 2009</p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="http://www.phparch.com/magazine/2009-2/june/">php|architect:
            Zend Framework</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata">June 2009</p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="http://www.phparch.com/magazine/2009-2/february/">php|architect: Optimizing Dojo and Zend Framework Integration</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic">
                February 2009
            </p>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><i>The PHP Anthology: 101 Essential Tips, Tricks & Hacks,  2nd Edition</i></h5> 

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic"> 
                with Ben Balbo, Harry Fuecks, Davey Shafik, and Ligaya Turmelle<br /> 
                October, 2007<br /> 
                SitePoint Pty, Ltd, Australia
            </p> 

            <p> 
                Contributed three chapters to this edition, including Chapter 3,
                "Error Handling"; Chapter 12, "XML and Web Services"; and Chapter
                13, "Best Practices".
            </p> 
        </div> 
    </div> 
</section>

<section>
    <h3 id="oss">Open Source Contributions</h3> 
    
    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://github.com/weierophinney">GitHub</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            Contributions made via <a href="http://github.com/">GitHub</a>.
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://github.com/phly/keep-a-changelog">Keep A Changelog CLI tooling</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            CLI tooling for creating and manpiulating CHANGELOG files following the
            <a href="https://keepachangelog.com">Keep A Changelog</a> format. The
            tooling is written in PHP, and covers additional features such as
            tagging releases and creating releases on GitHub and GitLab.
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://getlaminas.org/">Laminas Project</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            Project Lead since project was launched; I facilitate the work
            of maintainers and contributors, and act as liaison to the Linux Foundation.
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://docs.mezzio.dev/">Mezzio</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            (Formerly <em>Expressive</em>)<br/>
            Middleware microframework for PHP using the
            <a href="https://www.php-fig.org/psr/psr-7/">PSR-7 (HTTP message interfaces)</a>,
            <a href="https://www.php-fig.org/psr/psr-17/">PSR-17 (HTTP request factories)</a>,
            <a href="https://www.php-fig.org/psr/psr-11/">PSR-11 (Container interface)</a>,
            and <a href="https://www.php-fig.org/psr/psr-15/">PSR-15 (HTTP request handlers and middleware)</a>.
            Contributions have been made since the project began.
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://api-tools.getlaminas.org.org/">Laminas API Tools</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            (Formerly <em>Apigility</em>)<br />
            API builder and runtime engine, built on top of the Laminas Project
            MVC framework. Contributions have been made since before the
            project began, as it was forked from an experiment of my own.
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://framework.zend.com/">Zend Framework</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            Contributions were made starting in January 2006:

            <ul>
                <li>From January 2006 &#8212; April 2008, as PHP Developer for
                    Zend Technologies</li>
                <li>From April 2008 &#8212; March 2009, as Software Architect for
                    Zend Framework</li>
                <li>From April 2009 &#8212; December 2019, as Project Lead for
                    Zend Framework</li>
            </ul>
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="https://github.com/weierophinney/phly_mustache">Phly_Mustache</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            PHP implementation of <a href="http://mustache.github.com">Mustache</a>,
            a templating language.
        </div>
    </div>

    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="http://pear.php.net/">PEAR</a></h5> 

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic"> 
                July 13, 2005 &#8212; July 24, 2007
            </p> 

            <p> 
                Lead maintainer for <a href="http://pear.php.net/packages/File_Fortune">File_Fortune</a>.
            </p> 
        </div> 
    </div>
        
    <div class="flex flex-col lg:flex-row border-t border-dotted gap-4 mb-8">
        <h5 class="w-full lg:w-1/4 mt-4 font-serif"><a href="http://cgiapp.sourceforge.net/">Cgiapp</a></h5>

        <div class="w-full lg:w-2/3 lg:mt-4">
            <p class="metadata italic"> 
                March 2004 &#8212; March 2006
            </p> 

            <p> 
                PHP port of the perl module CGI::Application.
            </p> 
        </div> 
    </div> 
</section>
