<?php $this->layout('layout::layout', [
    'title' => 'Admin - Clear Response Cache',
]) ?>
<section class="admin col-md-6">
    <div class="card">
        <div class="card-header">
            <h4>Clear response cache complete</h4>
        </div>

        <ul class="list-group list-group-flush">
            <li class="list-group-item"><a href="<?= $this->url('admin') ?>">Back to admin</a></li>
        </ul>
    </div>
</section>
