<?php $this->layout('layout::layout', [
    'title' => 'Admin - Clear Response Cache',
]) ?>
<section class="w-1/3 mt-24 mx-auto flex flex-row justify-items-center">
    <div class="bg-neutral-700 p-4 w-full">
        <h4>Clear response cache complete</h4>

        <div class="bg-neutral-800 gap-4 divide-y divide-neutral-500 divide-solid">
            <a class="block p-2" href="<?= $this->url('admin') ?>">Back to admin</a>
        </div>
    </div>
</section>
