<?php
$this->layout('layout::layout', [
    'title' => $title,
]);

$this->push('styles');
echo $this->fetch('blog::styles');
$this->end();

$this->push('links');
if (isset($tag)) :
?>
    <link href="<?= $rss ?>" rel="alternate" type="application/rss+xml" title="phly, boy, phly RSS Feed for <?= $this->escapeHtmlAttr($tag) ?>">
    <link href="<?= $atom ?>" rel="alternate" type="application/atom+xml" title="phly, boy, phly Atom Feed for <?= $this->escapeHtmlAttr($tag) ?>">
<?php
endif;
$this->end();

$this->push('scripts');
echo $this->fetch('blog::scripts');
$this->end();

$this->push('footer');
echo $this->fetch('data::tag-cloud');
$this->end();
?>
<section class="blog center-block">
  <div class="container-fluid"><div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1><?= $this->escapeHtml($title) ?></h1>
    </div>
  </div></div>

  <?php if (empty($posts)) : ?>
  <p>No posts found.</p>

  <?php else : ?>
  <?php foreach ($posts as $post) : ?>
  <div class="container-fluid h-entry">
    <aside class="col-md-2 col-md-offset-2 hidden-xs alpha sidebar blog">
      <p>
        Written on <time class="dt-published" datetime="<?= $post->created_rfc() ?>"><?= $post->created() ?></time>.
        <?php
        $updated = $post->updated();
        if ($updated) : ?>
        <br />Last updated on <time class="dt-updated" datetime="<?= $updated['rfc'] ?>"><?= $updated['when'] ?></time>.
        <?php endif ?>
      </p>

      <ul class="tags">
      <?php foreach ($post->tags() as $tag) : ?>
        <li><a class="p-category" href="<?= $tag['link'] ?>"><?= $this->escapeHtml($tag['tag']) ?></a>
      <?php endforeach ?>
      </ul>

      <div class="p-author h-card hidden">
        Posted by <a rel="author" class="u-url" href="<?= $this->serverurl() ?>">Matthew Weier O'Phinney</a>,
        <img class="u-photo photo" width="50" src="https://avatars0.githubusercontent.com/u/25943?v=3&u=79dd2ea1d4d8855944715d09ee4c86215027fa80&s=140" alt="mwop">
      </div>
    </aside>

    <section class="col-md-8 omega post-list">
      <h4 class="entry"><a class="u-url u-uid" href="<?= $this->url('blog.post', ['id' => $post->id]) ?>"><?= $this->escapeHtml($post->title) ?></a></h4>

      <div class="entry body p-summary"><?= $post->body ?></div>

      <p><a href="<?= $this->url('blog.post', ['id' => $post->id]) ?>">Continue reading...</a></p>
    </section>
  </div>
  <?php endforeach ?>
  <?php endif ?>

  <?php $this->insert('mwop::pagination', ['pagination' => $pagination]) ?>
</section>
