<?php
$this->layout('layout::amp', [
    'title' => $post->title,
    'canonical' => $this->serverurl($this->postUrl($post)),
]);

$this->start('metadata');
?>
    {
      "@context": "http://schema.org",
      "@type": "BlogPosting",
      "@id": "<?= $this->serverurl($this->postUrl($post)) ?>",
      "headline": "<?= $post->title ?>",
      "datePublished": "<?= $this->formatDateRfc($post->created) ?>",
    <?php if ($post->updated) :?>
      "dateModified": "<?= $this->formatDateRfc($post->updated) ?>",
    <?php endif ?>
      "image": {
        "@type": "ImageObject",
        "url": "<?= $this->serverurl('/images/mwop-hard-rock-stack-2015.jpg') ?>",
        "height": 576,
        "width": 1023
      },
      "author": {
        "@type": "Person",
        "name": "Matthew Weier O'Phinney",
        "image": "https://avatars0.githubusercontent.com/u/25943?v=3&u=79dd2ea1d4d8855944715d09ee4c86215027fa80&s=140",
        "url": "<?= $this->serverurl() ?>"
      },
      "publisher": {
        "@type": "Organization",
        "name": "mwop.net",
        "image": "https://avatars0.githubusercontent.com/u/25943?v=3&u=79dd2ea1d4d8855944715d09ee4c86215027fa80&s=140",
        "url": "<?= $this->serverurl() ?>",
        "logo": {
            "@type": "ImageObject",
            "url": "<?= $this->serverurl('/images/favicon/favicon-32x32.png') ?>",
            "height": 32,
            "width": 32
        }
      },
      "keywords": "<?= implode(', ', $post->tags) ?>",
      "mainEntityOfPage": "<?= $this->serverurl($this->postUrl($post)) ?>"
    }
<?php $this->stop() ?>
<article class="single-entry h-entry col-md-6 blog">
    <h2 class="p-name"><a class="u-url u-uid" href="<?= $this->serverurl($this->postUrl($post)) ?>"><?= $this->escapeHtml($post->title) ?></a></h2>

    <div class="e-content">
    <?= $this->ampifyContent($post->body) ?>

    <?= $this->ampifyContent($post->extended) ?>
    </div>

    <div class="p-author h-card hidden">
      Posted by <a class="p-name u-url" href="<?= $this->serverurl() ?>">Matthew Weier O'Phinney</a>,
      <amp-img class="u-photo photo" width="50" height="50" src="https://avatars0.githubusercontent.com/u/25943?v=3&u=79dd2ea1d4d8855944715d09ee4c86215027fa80&s=140" alt="mwop"></amp-img>
    </div>
</article>
