<?php
return array (
  'Comic\\Comic' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'Comic.php',
  'Comic\\ComicDescription' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicDescription.php',
  'Comic\\ComicSource\\GarfieldMinusGarfield' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'GarfieldMinusGarfield.php',
  'Comic\\ComicSource\\GoComics' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'GoComics.php',
  'Comic\\ComicSource\\ForBetterOrForWorse' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'ForBetterOrForWorse.php',
  'Comic\\ComicSource\\ScenesFromAMultiverse' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'ScenesFromAMultiverse.php',
  'Comic\\ComicSource\\PennyArcade' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'PennyArcade.php',
  'Comic\\ComicSource\\Xkcd' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'Xkcd.php',
  'Comic\\ComicSource\\AbstractComicSource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'AbstractComicSource.php',
  'Comic\\ComicSource\\NotInventedHere' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'NotInventedHere.php',
  'Comic\\ComicSource\\Dilbert' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'Dilbert.php',
  'Comic\\ComicSource\\FoxTrot' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'FoxTrot.php',
  'Comic\\ComicSource\\UserFriendly' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'UserFriendly.php',
  'Comic\\ComicSource\\BasicInstructions' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'BasicInstructions.php',
  'Comic\\ComicSource\\CtrlAltDel' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'CtrlAltDel.php',
  'Comic\\ComicSource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicSource.php',
  'Comic\\ComicFactory' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Comic' . DIRECTORY_SEPARATOR . 'ComicFactory.php',
);