<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'GithubFeed\AtomReader' => __DIR__ . '/src/GithubFeed/AtomReader.php',
    'GithubFeed\FetchController' => __DIR__ . '/src/GithubFeed/FetchController.php',
);
