<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Blog\Exception\UnauthorizedAccessException'  => __DIR__ . '/src/Blog/Exception/UnauthorizedAccessException.php',
    'Blog\Filter\EntryFilter'                     => __DIR__ . '/src/Blog/Filter/EntryFilter.php',
    'Blog\Filter\Tags'                            => __DIR__ . '/src/Blog/Filter/Tags.php',
    'Blog\Filter\Permalink'                       => __DIR__ . '/src/Blog/Filter/Permalink.php',
    'Blog\Compiler\SortedEntries'                 => __DIR__ . '/src/Blog/Compiler/SortedEntries.php',
    'Blog\Compiler\PhpFileFilter'                 => __DIR__ . '/src/Blog/Compiler/PhpFileFilter.php',
    'Blog\Exception'                              => __DIR__ . '/src/Blog/Exception.php',
    'Blog\Controller\EntryController'             => __DIR__ . '/src/Blog/Controller/EntryController.php',
    'Blog\Compiler'                               => __DIR__ . '/src/Blog/Compiler.php',
    'Blog\EntryResource'                          => __DIR__ . '/src/Blog/EntryResource.php',
    'Blog\EntryEntity'                            => __DIR__ . '/src/Blog/EntryEntity.php',
    'Blog\EventListeners\EntryControllerListener' => __DIR__ . '/src/Blog/EventListeners/EntryControllerListener.php',
);