<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Blog\Filter\EntryFilter'                     => __DIR__ . '/src/Blog/Filter/EntryFilter.php',
    'Blog\Filter\Tags'                            => __DIR__ . '/src/Blog/Filter/Tags.php',
    'Blog\Filter\Permalink'                       => __DIR__ . '/src/Blog/Filter/Permalink.php',
    'Blog\Compiler\SortedEntries'                 => __DIR__ . '/src/Blog/Compiler/SortedEntries.php',
    'Blog\Compiler\PhpFileFilter'                 => __DIR__ . '/src/Blog/Compiler/PhpFileFilter.php',
    'Blog\Compiler'                               => __DIR__ . '/src/Blog/Compiler.php',
    'Blog\EntryEntity'                            => __DIR__ . '/src/Blog/EntryEntity.php',
);
