<?php $this->headTitle()->prepend('Login') ?>
<section class="authentication">
<?php if ($this->success): ?>
<h2>Logged in!</h2>

<p>
    You have successfully logged in.
</p>
<?php elseif ($this->error): ?>
<h2>Error!</h2>

<p><?php echo $this->message ?></p>

<?php
$form = $this->form;
echo $form->render($this);
?>
<?php else: ?>
<h2>Log in</h2>

<p>Please provide your credentials below.</p>
<?php
$form = $this->form;
echo $form->render($this);
?>
<?php endif ?>
</section>
