<?php
$resumeUrl = $this->url('resume');
?>
<p>
    I'm a husband, father of two, plaything of a Basset puppy, and web 
    architect by day.
</p>

<ul class="resume">
    <li><a href="<?php echo $resumeUrl ?>">Resume</a></li>
    <li><a href="http://twitter.com/weierophinney">Twitter</a></li>
    <li><a href="http://www.linkedin.com/in/mweierophinney">LinkedIn</a></li>
    <li><a href="http://www.ohloh.net/accounts/weierophinney">OhLoh</a></li>
    <li><a href="http://resume.github.com/?weierophinney">GitHub</a></li>
</ul>

