<?php 
$url        = $this->plugin('url');
$homeUrl    = $url(array(), array('name' => 'home'));
$blogUrl    = '/blog' /*$url(array(), array('name' => 'blog')) */;
$comicsUrl  = $url(array(), array('name' => 'comics'));
$resumeUrl  = $url(array(), array('name' => 'resume'));
$contactUrl = $url(array(), array('name' => 'contact-form'));
$content    = $this->content;
$footer     = $this->raw('footer');

$headLink = $this->plugin('headLink');
$headLink->prependStylesheet('/css/Application/site.css')
         ->prependStylesheet('/css/SkeletonCss/layout.css')
         ->prependStylesheet('/css/SkeletonCss/skeleton.css')
         ->prependStylesheet('/css/SkeletonCss/base.css');

$dojo = $this->plugin('dojo');
$modulePaths = $dojo->getDjConfigOption('modulePaths', array());
$modulePaths['Application'] = '/js/Application';
$dojo->setDjConfigOption('baseUrl', '/js/dojo/')
     ->setDjConfigOption('modulePaths', $modulePaths)
     ->requireModule('Application.scroll');

echo $this->doctype() ?>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
    <?php echo $this->headTitle() ?>

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <?php echo $headLink ?>

    <?php echo $this->dojo() ?>

    <?php echo $this->headScript() ?>

    <?php echo $this->render('search.phtml') ?>

    <?php echo $this->render('analytics.phtml') ?>

</head>
<body>
<div class="container">
    <header class="sixteen columns">
    <a href="<?php echo $homeUrl ?>"><img src="/images/Application/logo.gif" height="37" width="37"/></a>
        <span class="main_title">phly, boy, phly: matthew weier o'phinney</span>
    </header>

    <div class="sixteen columns" id="menu">
        <nav>
            <li><a href="<?php echo $homeUrl ?>">Home</a></li>
            <li><a href="<?php echo $blogUrl ?>">Blog</a></li>
            <?php /* <li><a href="<?php echo $comicsUrl ?>">Comics</a></li> */ ?>
            <li><a href="<?php echo $resumeUrl ?>">R&eacute;sum&eacute;</a></li>
            <li><a href="<?php echo $contactUrl ?>">Contact</a></li>
        </nav>
    </div>

    <div class="sixteen columns content">
        <?php echo $this->raw('content') ?>
    </div>

    <footer class="sixteen columns footer">
        <div class="column one-third alpha about">
            <h4>About</h4>
            <?php echo $this->render('about.phtml') ?>
        </div>

        <div class="column one-third projects">
            <h4>Projects</h4>
            <?php echo $this->render('projects.phtml') ?>
        </div>

        <div class="column one-third omega tags">
        <?php 
            echo $this->render('searchbox.phtml');
            if (is_string($footer)) {
                echo $this->vars()->escape($footer);
            }
            if (is_callable($footer)) {
                echo call_user_func($footer);
            } elseif (is_object($footer) && method_exists($footer, '__toString'))  {
                echo $footer;
            }
        ?>
        </div>
    </footer>
</div>
</body>
</html>
