<?php 
$url        = $this->plugin('url');
$homeUrl    = $url('home');
$blogUrl    = $url('phly-blog/index');
$comicsUrl  = $url('comics');
$resumeUrl  = $url('resume');
$contactUrl = $url('contact');
$content    = $this->content;
$footer     = $this->footer;

$headLink = $this->plugin('headLink');
$headLink->prependStylesheet('/css/Application/site.css')
         ->prependStylesheet('/css/SkeletonCss/layout.css')
         ->prependStylesheet('/css/SkeletonCss/skeleton.css')
         ->prependStylesheet('/css/SkeletonCss/base.css');

$this->headScript()->prependFile('/js/dojo/dojo.js');
$this->headScript()->prependScript($this->render('dojo-config'));
$this->headScript()->appendScript('require(["Application/scroll"], function(scroll) {});');

echo $this->doctype() ?>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
    <?php echo $this->headTitle() ?>

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <?php echo $headLink ?>

    <?php echo $this->headScript() ?>

    <?php echo $this->render('search.phtml') ?>

    <?php echo $this->render('analytics.phtml') ?>

</head>
<body>
<div class="container">
    <header class="sixteen columns">
    <a href="<?php echo $homeUrl ?>"><img src="/images/Application/logo.gif" height="37" width="37" alt="Celtic Knot" /></a>
        <span class="main_title">phly, boy, phly: matthew weier o'phinney</span>
    </header>

    <div class="sixteen columns" id="menu">
        <nav><ul>
            <li><a href="<?php echo $homeUrl ?>">Home</a></li>
            <li><a href="<?php echo $blogUrl ?>">Blog</a></li>
            <?php /* <li><a href="<?php echo $comicsUrl ?>">Comics</a></li> */ ?>
            <li><a href="<?php echo $resumeUrl ?>">R&eacute;sum&eacute;</a></li>
            <li><a href="<?php echo $contactUrl ?>">Contact</a></li>
        </ul></nav>
    </div>

    <div class="sixteen columns content">
        <?php echo $this->content ?>
    </div>

    <footer class="sixteen columns footer">
        <div class="column one-third alpha about">
            <h4>About</h4>
            <?php echo $this->render('about.phtml') ?>
        </div>

        <div class="column one-third projects">
            <h4>Projects</h4>
            <?php echo $this->render('projects.phtml') ?>
        </div>

        <div class="column one-third omega tags">
        <?php 
            echo $this->render('searchbox.phtml');
            if (!empty($footer)) {
                echo $footer;
            }
        ?>
        </div>
    </footer>
</div>
</body>
</html>
