<ul class="projects">
    <li><a href="http://framework.zend.com/">Zend Framework (Project Lead)</a></li>
    <li><a href="http://www.the-pastry-box-project.net/baker/matthew-weier-ophinney/">The Pastry Box Project</a> (as a Baker)</li>
    <li><a href="http://github.com/weierophinney/phly_mustache">Phly_Mustache</a></li>
    <li>ZF2 Modules
    <ul>
        <li><a href="https://github.com/weierophinney/PhlyContact">PhlyContact</a></li>
        <li><a href="https://github.com/weierophinney/PhlyBlog">PhlyBlog</a></li>
        <li><a href="https://github.com/weierophinney/PhlyPeep">PhlyPeep</a> (demo purposes only)</li>
    </ul>
    </li>
</ul>

