<?php $this->layout('layout::layout', [
    'title' => 'Unauthorized',
]); ?>

<section class="col-md-8 col-md-offset-2 code_401">
  <h2>Unauthorized</h2>

  <p>
    <?php if ($error) : ?>
    <strong class="text-danger">An error occurred: <?= $this->escapeHtml($error) ?></strong>
    <?php else : ?>
    You are not logged in, and therefore cannot perform this action.
    <?php endif ?>
  </p>

  <p>
    Login to continue:
  <p>

  <div class="btn-group-vertical" role="group">
    <a class="btn btn-default" href="<?= $auth_path ?>/github?redirect=<?= $redirect ?>">GitHub</a>
    <a class="btn btn-default" href="<?= $auth_path ?>/google?redirect=<?= $redirect ?>">Google</a>
    <?php if ($debug) : ?>
    <a class="btn btn-default" href="<?= $auth_path ?>/debug?redirect=<?= $redirect ?>">Debug</a>
    <?php endif ?>
  </div>
</section>
