<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PhlyBlog\Filter\EntryFilter'       => __DIR__ . '/src/PhlyBlog/Filter/EntryFilter.php',
    'PhlyBlog\Filter\Tags'              => __DIR__ . '/src/PhlyBlog/Filter/Tags.php',
    'PhlyBlog\Filter\Permalink'         => __DIR__ . '/src/PhlyBlog/Filter/Permalink.php',
    'PhlyBlog\Compiler\WriterInterface' => __DIR__ . '/src/PhlyBlog/Compiler/WriterInterface.php',
    'PhlyBlog\Compiler\FileWriter'      => __DIR__ . '/src/PhlyBlog/Compiler/FileWriter.php',
    'PhlyBlog\Compiler\SortedEntries'   => __DIR__ . '/src/PhlyBlog/Compiler/SortedEntries.php',
    'PhlyBlog\Compiler\PhpFileFilter'   => __DIR__ . '/src/PhlyBlog/Compiler/PhpFileFilter.php',
    'PhlyBlog\Compiler'                 => __DIR__ . '/src/PhlyBlog/Compiler.php',
    'PhlyBlog\CompilerOptions'          => __DIR__ . '/src/PhlyBlog/CompilerOptions.php',
    'PhlyBlog\EntryEntity'              => __DIR__ . '/src/PhlyBlog/EntryEntity.php',
);
