<?php 
$url        = $this->plugin('url');
$homeUrl    = $url(array(), array('name' => 'home'));
$blogUrl    = $url(array(), array('name' => 'blog'));
$comicsUrl  = $url(array(), array('name' => 'comics'));
$resumeUrl  = $url(array(), array('name' => 'resume'));
$contactUrl = $url(array(), array('name' => 'contact-form'));
$content    = $this->content;
$footer     = $this->footer;

$headLink = $this->plugin('headLink');
$headLink->prependStylesheet('/css/Application/site.css')
         ->prependStylesheet('/css/Application/960.css')
         ->prependStylesheet('/css/Application/text.css')
         ->prependStylesheet('/css/Application/reset.css');

echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    
    <?php echo $headLink ?>

    <?php echo $this->dojo() ?>

    <?php echo $this->headScript() ?>

    <?php echo $this->render('search.phtml') ?>

</head>
<body>
<div class="container_12">
    <div class="grid_12" id="header">
    <a href="<?php echo $homeUrl ?>"><img src="/images/Application/logo.gif" height="37" width="37"/></a>
        <span class="main_title">phly, boy, phly: matthew weier o'phinney</span>
    </div>

    <div class="grid_12" id="menu">
        <ul>
            <li><a href="<?php echo $homeUrl ?>">Home</a></li>
            <li><a href="<?php echo $blogUrl ?>">Blog</a></li>
            <li><a href="<?php echo $comicsUrl ?>">Comics</a></li>
            <li><a href="<?php echo $resumeUrl ?>">R&eacute;sum&eacute;</a></li>
            <li><a href="<?php echo $contactUrl ?>">Contact</a></li>
        </ul>
    </div>

    <?php echo $this->raw('content') ?>
    <div class="clear"></div>

    <div class="grid_12 divider">&nbsp;</div>

    <div class="grid_4 footer about">
        <h4>About</h4>
        <?php echo $this->render('about.phtml') ?>
    </div>

    <div class="grid_4 footer projects">
        <h4>Projects</h4>
        <?php echo $this->render('projects.phtml') ?>
    </div>

    <div class="grid_4 footer tags">
<?php 
    echo $this->render('searchbox.phtml');
    if (is_string($footer)) {
        echo $this->vars()->escape($footer);
    }
    if (is_callable($footer)) {
        echo call_user_func($footer);
    } elseif (is_object($footer) && method_exists($footer, '__toString'))  {
        echo $footer;
    }
?>
    </div>
    <div class="grid_12 divider">&nbsp;</div>
    
    <div class="grid_12 mobile">
        <a href="/mobile">iPhone layout</a> | <a href="/mobile?theme=android">Android layout</a>
    </div>
</div>
</body>
</html>
