<?php
$url        = $this->plugin('url');
$homeUrl    = $url(array(), array('name' => 'home'));
$blogUrl    = $url(array(), array('name' => 'blog'));
$comicsUrl  = $url(array(), array('name' => 'comics'));
$resumeUrl  = $url(array(), array('name' => 'resume'));
$contactUrl = $url(array(), array('name' => 'contact-form'));
$vars       = $this->placeholder('layout');
$theme      = $vars->mobile->theme;
$content    = $this->raw('content');

$dojo = $this->dojo();
$dojo->setDjConfigOption('parseOnLoad', false);
$dojo->requireModule('dojox.mobile.parser')
     ->requireModule('dojox.mobile')
     ->requireModule('dojox.mobile.ScrollableView');
$dojo->addJavascript('
    // If not a WebKit-based client, load compat
    dojo.requireIf(!dojo.isWebKit, "dojox.mobile.compat")

    dojo.ready(function() {
        /* Place sidebars following their parent, and make them a RoundRect */
        dojo.query("div.sidebar").forEach(function(n) {
            dojo.place(n, n.parentNode, "after");
            dojo.attr(n, "dojoType", "dojox.mobile.RoundRect");
        });

        /* Parse widgets */
        dojox.mobile.parser.parse();
    });
');
?>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes" />

    <?php echo $this->headTitle() ?>

    <?php echo $this->headLink() ?>

    <link href="http://ajax.googleapis.com/ajax/libs/dojo/1.6/dojox/mobile/themes/<?php echo $theme ?>/<?php echo $theme ?>.css" rel="stylesheet"></link>
    <link href="http://ajax.googleapis.com/ajax/libs/dojo/1.6/dojox/mobile/themes/domButtons.css" rel="stylesheet"></link>
    
    <?php echo $dojo; ?>

</head>
<body>
<div dojoType="dojox.mobile.ScrollableView" selected="true">
    <h1 dojoType="dojox.mobile.Heading">
        phly, boy, phly
    </h1>

    <div dojoType="dojox.mobile.RoundRect">
        <?php echo $content ?>
    </div>

    <ul dojoType="dojox.mobile.RoundRectList">
        <li dojoType="dojox.mobile.ListItem"><a href="<?php echo $homeUrl ?>">Home</a></li>
        <li dojoType="dojox.mobile.ListItem"><a href="<?php echo $blogUrl ?>">Blog</a></li>
        <li dojoType="dojox.mobile.ListItem"><a href="<?php echo $comicsUrl ?>">Comics</a></li>
        <li dojoType="dojox.mobile.ListItem"><a href="<?php echo $resumeUrl ?>">R&eacute;sum&eacute;</a></li>
        <li dojoType="dojox.mobile.ListItem"><a href="<?php echo $contactUrl ?>">Contact</a></li>
    </ul>
</div>
</body>
</html>
