<p>
    I'm a husband, a father of two, and web architect by day.
</p>

<ul>
    <li><a href="<?= $this->url('now') ?>">What I'm doing now</a></li>
    <li><a href="<?= $this->url('resume') ?>">Resume</a></li>
    <li><a href="https://twitter.com/mwop">Twitter (@mwop)</a></li>
    <li><a href="https://instagram.com/phlytangle">Instagram (@phlytangle)</a></li>
    <li><a href="https://github.com/weierophinney">GitHub (@weierophinney)</a></li>
</ul>

<?php /*
<p><a href="https://www.patreon.com/mwop"><img class="max-width" src="/images/become_a_patron_button@2x.png" alt="Become a Patron!" /></a></p>
 */ ?>
