<p>
    I'm a husband, a father of two, and web architect by day.
</p>

<ul class="font-sans">
    <li><a href="<?= $this->url('now') ?>">What I'm doing now</a></li>
    <li><a href="<?= $this->url('resume') ?>">Resume</a></li>
    <li><a href="https://twitter.com/mwop">Twitter (@mwop)</a></li>
    <li><a rel="me" href="https://phpc.social/@mwop">@mwop@phpc.social (Mastodon)</a></li>
    <li><a href="https://instagram.com/phlytangle">Instagram (@phlytangle)</a></li>
    <li><a href="https://github.com/weierophinney">GitHub (@weierophinney)</a></li>
</ul>

