<footer class="bg-dark container-fluid">
  <div class="row align-items-start">
    <div class="col alpha about">
      <h4>About</h4>
      <?php $this->insert('layout::about') ?>
    </div>

    <div class="col projects">
      <h4>Projects</h4>
      <?php $this->insert('layout::projects') ?>
    </div>

    <div class="col omega tags">
      <?= $footer ?? '&nbsp;' ?>
    </div>
  </div>

  <div class="row copyright align-items-end">
    <div class="col-12 text-center">
      Unless otherwise noted, &#169; Matthew Weier O'Phinney
    </div>
  </div>
</footer>
