<footer class="flex-col w-full mt-auto bg-neutral-700 text-neutral-100">
  <div class="flex flex-row justify-between justify-items-stretch items-start px-4 py-4">
    <div class="w-fit md:w-1/2 lg:w-1/3 lg:max-w-[33%] about">
      <h4 class="text-2xl font-semibold">About</h4>
      <?php $this->insert('layout::about') ?>
    </div>

    <div class="w-fit md:w-1/2 lg:w-1/3 lg:max-w-[33%] projects">
      <h4 class="text-2xl font-semibold mb-2">Projects</h4>
      <?php $this->insert('layout::projects') ?>
    </div>

    <div class="w-fit md:w-1/2 lg:w-1/3 lg:max-w-[50%] lg:max-w-[33%]">
    <?php if ($footer): ?>
      <?= $footer ?>
    <?php else: ?>
      <div class="w-full">&nbsp;</div>
    <?php endif ?>
    </div>
  </div>

  <div class="copyright">
    <div class="min-w-full text-center mt-4">
      Unless otherwise noted, &#169; Matthew Weier O'Phinney
    </div>
  </div>
</footer>
