<nav class="bg-mwop-nav shadow-lg p-2 mt-0 fixed w-full z-10 top-0" role="navigation">
  <div class="w-full mx-auto px-4">
    <div class="flex justify-between items-center">
      <div class="flex space-x-7">
        <div>
          <a class="no-underline flex items-center py-4 hover:font-normal" href="<?= $this->url('home') ?>">
            <img class="w-9 h-9" src="/images/logo.gif" alt="Celtic Knot - Matthew Weier O'Phinney" />
            <span class="inline-block pl-4 xl:hidden text-mwop-fg hover:text-white">mwop.net</span>
            <span class="hidden xl:inline-block xl:pl-4 text-mwop-fg hover:text-white">matthew weier o'phinney</span>
          </a>
        </div>

        <div class="hidden md:flex items-center space-x-1">
          <a class="py-4 px-2 font-semibold no-underline" href="<?= $this->url('blog') ?>">Blog</a>
          <a class="py-4 px-2 font-semibold no-underline" href="<?= $this->url('art.gallery') ?>">Art</a>
          <a class="py-4 px-2 font-semibold no-underline" href="<?= $this->url('resume') ?>">R&eacute;sum&eacute;</a>
          <a class="py-4 px-2 font-semibold no-underline" href="<?= $this->url('contact') ?>">Contact</a>
        </div>
      </div>

      <div class="hidden md:block md:space-x-3">
        <form class="flex flex-col search">
          <input class="text-input mt-2 mb-0 appearance-none rounded-lg md:w-[15rem] lg:w-[25rem] placeholder-mwop-contrast" type="text" placeholder="Search..." aria-label="Search">

          <ul class="search-results"></ul>
        </form>
      </div>

      <div class="md:hidden flex items-center">
        <button class="outline-none mobile-menu-button">
          <svg class="w-6 h-6 text-mwop-osft hover:text-mwop-fg"
            x-show="!showMenu"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
    </div>

  </div>

  <!-- mobile menu -->
  <div class="hidden mobile-menu divide-y divide-neutral-300 divide-dotted">
    <a class="block border-t border-mwop-light border-dotted px-2 py-4 no-underline text-sm font-semibold text-mwop-light transition duration-300 hover:bg-mwop-fg hover:text-mwop-bg" href="<?= $this->url('blog') ?>">Blog</a>
    <a class="block px-2 py-4 no-underline text-sm font-semibold text-mwop-light transition duration-300 hover:bg-mwop-fg hover:text-mwop-bg" href="<?= $this->url('art.gallery') ?>">Art</a>
    <a class="block px-2 py-4 no-underline text-sm font-semibold text-mwop-light transition duration-300 hover:bg-mwop-fg hover:text-mwop-bg" href="<?= $this->url('resume') ?>">R&eacute;sum&eacute;</a>
    <a class="block px-2 py-4 no-underline text-sm font-semibold text-mwop-light transition duration-300 hover:bg-mwop-fg hover:text-mwop-bg" href="<?= $this->url('contact') ?>">Contact</a>
    <form class="search block flex-col">
        <input class="text-input appearance-none rounded-lg mt-2" type="text" placeholder="Search..." aria-label="Search">
        <ul class="search-results"></ul>
    </form>
  </div>
</nav>
