<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="copyright" content="Matthew Weier O'Phinney" />
  <meta name="author" content="Matthew Weier O'Phinney" />

  <title>phly, boy, phly :: <?= $title ?? 'home' ?></title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="twitter:site" content="@mwop">

  <?php // android theme color: http://updates.html5rocks.com/2014/11/Support-for-theme-color-in-Chrome-39-for-Android ?>
  <meta name="theme-color" content="#018401">
  <meta name="msapplication-TileColor" content="#ffffff">

  <?php // android install-to-homescreen https://developer.chrome.com/multidevice/android/installtohomescreen ?>
  <link rel="manifest" href="/manifest.json">

  <?php
  $this->insert('layout::favicon');
  $this->insert('layout::semantic');
  $this->insert('layout::styles', ['styles' => $this->section('styles')]);
  $this->insert('layout::links', ['links' => $this->section('links')]);
  ?>

   <meta name="ocs-site-verification" content="c4b02f596a79a562778389766296d956" />
</head>
<body class="bg-neutral-800 flex flex-col h-screen">
<?php $this->insert('layout::header') ?>
<div>
    <?= $this->section('content') ?>
</div>
<?php $this->insert('layout::footer', ['footer' => $this->section('footer')]) ?>
<?php $this->insert('layout::scripts', ['scripts' => $this->section('scripts')]) ?>
</body>
</html>
