<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="copyright" content="Matthew Weier O'Phinney" />
  <meta name="author" content="Matthew Weier O'Phinney" />

  <title>phly, boy, phly :: <?= $title ?? 'home' ?></title>

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="twitter:site" content="@mwop">

  <?php // android theme color: http://updates.html5rocks.com/2014/11/Support-for-theme-color-in-Chrome-39-for-Android ?>
  <meta name="theme-color" content="#018401">
  <meta name="msapplication-TileColor" content="#ffffff">

  <?php // android install-to-homescreen https://developer.chrome.com/multidevice/android/installtohomescreen ?>
  <link rel="manifest" href="/manifest.json">

  <?php
  $this->insert('layout::favicon');
  $this->insert('layout::semantic');
  $this->insert('layout::styles', ['styles' => $this->section('styles')]);
  $this->insert('layout::links', ['links' => $this->section('links')]);
  ?>

  <script src="/js/ga.js"></script>
</head>
<body>
<?php $this->insert('layout::header') ?>
<div class="container-fluid content-window">
  <div class="row content justify-content-center">
      <?= $this->section('content') ?>
  </div>
</div>
<?php
$this->insert('layout::footer', ['footer' => $this->section('footer')]);
$this->insert('layout::scripts', ['scripts' => $this->section('scripts')]);
?>
</body>
</html>
