  <link href="<?= $this->serverurl($this->url('blog.feed', ['type' => 'rss'])) ?>" rel="alternate" type="application/rss+xml" title="phly, boy, phly RSS Feed">
  <link href="<?= $this->serverurl($this->url('blog.feed', ['type' => 'atom'])) ?>" rel="alternate" type="application/atom+xml" title="phly, boy, phly Atom Feed">
  <link rel="me" href="https://phpc.social/@mwop" title="@mwop@phpc.social">
  <?= $links ?>
