<ul>
    <li><a href="https://docs.mezzio.dev/">Mezzio</a> (formerly Expressive; PSR-15 middleware framework)</li>
    <li><a href="https://api-tools.getlaminas.org/">Laminas API Tools</a> (formerly Apigility; MVC-driven API framework)</li>
    <li><a href="https://docs.laminas.dev/">Laminas Project</a> (formerly Zend Framework; component library and MVC framework)</li>
    <li><a href="https://docs.laminas.dev/laminas-stratigility/">Stratigility</a> (PSR-15 middleware for PHP)</li>
    <li><a href="https://docs.laminas.dev/laminas-diactoros/">Diactoros</a> (PSR-7 HTTP messages and PSR-17 HTTP message factories for PHP)</li>
    <li><a href="https://github.com/phly/keep-a-changelog">Keep-A-Changelog CLI tooling</a></li>
    <?php /* <li><a href="http://www.the-pastry-box-project.net/baker/matthew-weier-ophinney/">The Pastry Box Project 2012</a> (as a Baker)</li> Commented out 2021-11-16; DNS no longer resolves */ ?>
    <?php /* <li><a href="https://phly-mustache.readthedocs.io/en/latest/">phly-mustache</a> (<a href="http://mustache.github.io">mustache</a> templating for PHP)</li> Commented out 2021-11-16; have not maintained it actively in years */ ?>
</ul>

