  <?php // semantic web ?>
  <link rel="me" href="https://twitter.com/mwop" title="@mwop on Twitter">
  <link rel="me" href="https://phpc.social/@mwop" title="@mwop@phpc.social">
  <link rel="me" href="https://github.com/weierophinney" title="GitHub">
  <link rel="me" href="https://keybase.io/mwop" title="Keybase">
  <link rel="me" href="https://www.facebook.com/mweierophinney/" title="Facebook">
  <link rel="me" href="https://www.linkedin.com/in/mweierophinney/" title="LinkedIn">
