<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Mwop\OAuth2\CallbackHandler::class => Mwop\OAuth2\CallbackHandlerFactory::class,
            Mwop\OAuth2\CheckAuthenticationMiddleware::class => Mwop\OAuth2\CheckAuthenticationMiddlewareFactory::class,
            Mwop\OAuth2\RequestAuthenticationHandler::class => Mwop\OAuth2\RequestAuthenticationHandlerFactory::class,
        ],
    ],
];
