<?php if ($this->pageCount < 2) return ?>
<div class="paginationControl">
<?php // First page link
    if ($this->first && $this->first != $this->current): ?>
        <a href="<?php echo $this->url ?>" class="first">&lt;&lt; First</a> |
<?php endif;

    // Previous page
    if ($this->previous): ?>
        <a href="<?php echo $this->url . '?page=' . $this->previous ?>"> &lt; Previous </a> |
<?php endif;

    // Numbered page links
    foreach ($this->pagesInRange as $page):
        if ($page == $this->current): ?>
        <span class="current"><?php echo $page ?></span> |
        <?php else: ?>
        <a href="<?php echo $this->url . '?page=' . $page ?>"><?php echo $page ?></a> |
        <?php endif ?>
<?php endforeach;

    // Next page link
    if ($this->next): ?>
        <a href="<?php echo $this->url . '?page=' . $this->next ?>"> Next &gt;</a> |
<?php endif;

    // Last page link
    if ($this->last && $this->last !== $this->current): ?>
        <a href="<?php echo $this->url . '?page=' . $this->last ?>" class="last"> Last &gt;&gt;</a>
<?php endif; ?>
</div>

